// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code ApnItem}
 */
public  final class ApnItem extends
    com.google.protobuf.GeneratedMessageLite<
        ApnItem, ApnItem.Builder> implements
    // @@protoc_insertion_point(message_implements:ApnItem)
    ApnItemOrBuilder {
  private ApnItem() {
    name_ = "";
    value_ = "";
    type_ = emptyIntList();
    bearerBitmask_ = "";
    server_ = "";
    proxy_ = "";
    port_ = "";
    user_ = "";
    password_ = "";
    mmsc_ = "";
    mmscProxy_ = "";
    mmscProxyPort_ = "";
  }
  /**
   * Protobuf enum {@code ApnItem.ApnType}
   */
  public enum ApnType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ALL = 0;</code>
     */
    ALL(0),
    /**
     * <code>DEFAULT = 1;</code>
     */
    DEFAULT(1),
    /**
     * <code>MMS = 2;</code>
     */
    MMS(2),
    /**
     * <code>SUPL = 3;</code>
     */
    SUPL(3),
    /**
     * <code>DUN = 4;</code>
     */
    DUN(4),
    /**
     * <code>HIPRI = 5;</code>
     */
    HIPRI(5),
    /**
     * <code>FOTA = 6;</code>
     */
    FOTA(6),
    /**
     * <code>IMS = 7;</code>
     */
    IMS(7),
    /**
     * <code>CBS = 8;</code>
     */
    CBS(8),
    /**
     * <code>IA = 9;</code>
     */
    IA(9),
    /**
     * <code>EMERGENCY = 10;</code>
     */
    EMERGENCY(10),
    /**
     * <code>XCAP = 11;</code>
     */
    XCAP(11),
    /**
     * <code>UT = 12;</code>
     */
    UT(12),
    ;

    /**
     * <code>ALL = 0;</code>
     */
    public static final int ALL_VALUE = 0;
    /**
     * <code>DEFAULT = 1;</code>
     */
    public static final int DEFAULT_VALUE = 1;
    /**
     * <code>MMS = 2;</code>
     */
    public static final int MMS_VALUE = 2;
    /**
     * <code>SUPL = 3;</code>
     */
    public static final int SUPL_VALUE = 3;
    /**
     * <code>DUN = 4;</code>
     */
    public static final int DUN_VALUE = 4;
    /**
     * <code>HIPRI = 5;</code>
     */
    public static final int HIPRI_VALUE = 5;
    /**
     * <code>FOTA = 6;</code>
     */
    public static final int FOTA_VALUE = 6;
    /**
     * <code>IMS = 7;</code>
     */
    public static final int IMS_VALUE = 7;
    /**
     * <code>CBS = 8;</code>
     */
    public static final int CBS_VALUE = 8;
    /**
     * <code>IA = 9;</code>
     */
    public static final int IA_VALUE = 9;
    /**
     * <code>EMERGENCY = 10;</code>
     */
    public static final int EMERGENCY_VALUE = 10;
    /**
     * <code>XCAP = 11;</code>
     */
    public static final int XCAP_VALUE = 11;
    /**
     * <code>UT = 12;</code>
     */
    public static final int UT_VALUE = 12;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApnType valueOf(int value) {
      return forNumber(value);
    }

    public static ApnType forNumber(int value) {
      switch (value) {
        case 0: return ALL;
        case 1: return DEFAULT;
        case 2: return MMS;
        case 3: return SUPL;
        case 4: return DUN;
        case 5: return HIPRI;
        case 6: return FOTA;
        case 7: return IMS;
        case 8: return CBS;
        case 9: return IA;
        case 10: return EMERGENCY;
        case 11: return XCAP;
        case 12: return UT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApnType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApnType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApnType>() {
            @java.lang.Override
            public ApnType findValueByNumber(int number) {
              return ApnType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ApnTypeVerifier.INSTANCE;
    }

    private static final class ApnTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ApnTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ApnType.forNumber(number) != null;
            }
          };

    private final int value;

    private ApnType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ApnItem.ApnType)
  }

  /**
   * Protobuf enum {@code ApnItem.Protocol}
   */
  public enum Protocol
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>IP = 0;</code>
     */
    IP(0),
    /**
     * <code>IPV6 = 1;</code>
     */
    IPV6(1),
    /**
     * <code>IPV4V6 = 2;</code>
     */
    IPV4V6(2),
    /**
     * <code>PPP = 3;</code>
     */
    PPP(3),
    ;

    /**
     * <code>IP = 0;</code>
     */
    public static final int IP_VALUE = 0;
    /**
     * <code>IPV6 = 1;</code>
     */
    public static final int IPV6_VALUE = 1;
    /**
     * <code>IPV4V6 = 2;</code>
     */
    public static final int IPV4V6_VALUE = 2;
    /**
     * <code>PPP = 3;</code>
     */
    public static final int PPP_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Protocol valueOf(int value) {
      return forNumber(value);
    }

    public static Protocol forNumber(int value) {
      switch (value) {
        case 0: return IP;
        case 1: return IPV6;
        case 2: return IPV4V6;
        case 3: return PPP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Protocol> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
            @java.lang.Override
            public Protocol findValueByNumber(int number) {
              return Protocol.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ProtocolVerifier.INSTANCE;
    }

    private static final class ProtocolVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ProtocolVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Protocol.forNumber(number) != null;
            }
          };

    private final int value;

    private Protocol(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ApnItem.Protocol)
  }

  /**
   * Protobuf enum {@code ApnItem.Xlat}
   */
  public enum Xlat
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SKIP_464XLAT_DEFAULT = 0;</code>
     */
    SKIP_464XLAT_DEFAULT(0),
    /**
     * <code>SKIP_464XLAT_DISABLE = 1;</code>
     */
    SKIP_464XLAT_DISABLE(1),
    /**
     * <code>SKIP_464XLAT_ENABLE = 2;</code>
     */
    SKIP_464XLAT_ENABLE(2),
    ;

    /**
     * <code>SKIP_464XLAT_DEFAULT = 0;</code>
     */
    public static final int SKIP_464XLAT_DEFAULT_VALUE = 0;
    /**
     * <code>SKIP_464XLAT_DISABLE = 1;</code>
     */
    public static final int SKIP_464XLAT_DISABLE_VALUE = 1;
    /**
     * <code>SKIP_464XLAT_ENABLE = 2;</code>
     */
    public static final int SKIP_464XLAT_ENABLE_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Xlat valueOf(int value) {
      return forNumber(value);
    }

    public static Xlat forNumber(int value) {
      switch (value) {
        case 0: return SKIP_464XLAT_DEFAULT;
        case 1: return SKIP_464XLAT_DISABLE;
        case 2: return SKIP_464XLAT_ENABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Xlat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Xlat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Xlat>() {
            @java.lang.Override
            public Xlat findValueByNumber(int number) {
              return Xlat.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return XlatVerifier.INSTANCE;
    }

    private static final class XlatVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new XlatVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Xlat.forNumber(number) != null;
            }
          };

    private final int value;

    private Xlat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ApnItem.Xlat)
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    name_ = value;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    name_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.lang.String value_;
  /**
   * <code>required string value = 2;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <code>required string value = 2;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <code>required string value = 2;</code>
   * @param value The value to set.
   */
  private void setValue(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    value_ = value;
  }
  /**
   * <code>required string value = 2;</code>
   */
  private void clearValue() {
    bitField0_ = (bitField0_ & ~0x00000002);
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <code>required string value = 2;</code>
   * @param value The bytes for value to set.
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    value_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList type_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType> type_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType>() {
            @java.lang.Override
            public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType convert(java.lang.Integer from) {
              com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType result = com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType.forNumber(from);
              return result == null ? com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType.ALL : result;
            }
          };
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   * @return A list containing the type.
   */
  @java.lang.Override
  public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType> getTypeList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType>(type_, type_converter_);
  }
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   * @return The count of type.
   */
  @java.lang.Override
  public int getTypeCount() {
    return type_.size();
  }
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   * @param index The index of the element to return.
   * @return The type at the given index.
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType getType(int index) {
    com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType result = com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType.forNumber(type_.getInt(index));
    return result == null ? com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType.ALL : result;
  }
  private void ensureTypeIsMutable() {
    com.google.protobuf.Internal.IntList tmp = type_;
    if (!tmp.isModifiable()) {
      type_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   * @param index The index to set the value at.
   * @param value The type to set.
   */
  private void setType(
      int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType value) {
    value.getClass();
  ensureTypeIsMutable();
    type_.setInt(index, value.getNumber());
  }
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   * @param value The type to add.
   */
  private void addType(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType value) {
    value.getClass();
  ensureTypeIsMutable();
    type_.addInt(value.getNumber());
  }
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   * @param values The type to add.
   */
  private void addAllType(
      java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType> values) {
    ensureTypeIsMutable();
    for (com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType value : values) {
      type_.addInt(value.getNumber());
    }
  }
  /**
   * <code>repeated .ApnItem.ApnType type = 3;</code>
   */
  private void clearType() {
    type_ = emptyIntList();
  }

  public static final int BEARERBITMASK_FIELD_NUMBER = 4;
  private java.lang.String bearerBitmask_;
  /**
   * <code>optional string bearerBitmask = 4;</code>
   * @return Whether the bearerBitmask field is set.
   */
  @java.lang.Override
  public boolean hasBearerBitmask() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string bearerBitmask = 4;</code>
   * @return The bearerBitmask.
   */
  @java.lang.Override
  public java.lang.String getBearerBitmask() {
    return bearerBitmask_;
  }
  /**
   * <code>optional string bearerBitmask = 4;</code>
   * @return The bytes for bearerBitmask.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBearerBitmaskBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(bearerBitmask_);
  }
  /**
   * <code>optional string bearerBitmask = 4;</code>
   * @param value The bearerBitmask to set.
   */
  private void setBearerBitmask(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
    bearerBitmask_ = value;
  }
  /**
   * <code>optional string bearerBitmask = 4;</code>
   */
  private void clearBearerBitmask() {
    bitField0_ = (bitField0_ & ~0x00000004);
    bearerBitmask_ = getDefaultInstance().getBearerBitmask();
  }
  /**
   * <code>optional string bearerBitmask = 4;</code>
   * @param value The bytes for bearerBitmask to set.
   */
  private void setBearerBitmaskBytes(
      com.google.protobuf.ByteString value) {
    bearerBitmask_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static final int SERVER_FIELD_NUMBER = 5;
  private java.lang.String server_;
  /**
   * <code>optional string server = 5;</code>
   * @return Whether the server field is set.
   */
  @java.lang.Override
  public boolean hasServer() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string server = 5;</code>
   * @return The server.
   */
  @java.lang.Override
  public java.lang.String getServer() {
    return server_;
  }
  /**
   * <code>optional string server = 5;</code>
   * @return The bytes for server.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(server_);
  }
  /**
   * <code>optional string server = 5;</code>
   * @param value The server to set.
   */
  private void setServer(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
    server_ = value;
  }
  /**
   * <code>optional string server = 5;</code>
   */
  private void clearServer() {
    bitField0_ = (bitField0_ & ~0x00000008);
    server_ = getDefaultInstance().getServer();
  }
  /**
   * <code>optional string server = 5;</code>
   * @param value The bytes for server to set.
   */
  private void setServerBytes(
      com.google.protobuf.ByteString value) {
    server_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static final int PROXY_FIELD_NUMBER = 6;
  private java.lang.String proxy_;
  /**
   * <code>optional string proxy = 6;</code>
   * @return Whether the proxy field is set.
   */
  @java.lang.Override
  public boolean hasProxy() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string proxy = 6;</code>
   * @return The proxy.
   */
  @java.lang.Override
  public java.lang.String getProxy() {
    return proxy_;
  }
  /**
   * <code>optional string proxy = 6;</code>
   * @return The bytes for proxy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProxyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(proxy_);
  }
  /**
   * <code>optional string proxy = 6;</code>
   * @param value The proxy to set.
   */
  private void setProxy(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000010;
    proxy_ = value;
  }
  /**
   * <code>optional string proxy = 6;</code>
   */
  private void clearProxy() {
    bitField0_ = (bitField0_ & ~0x00000010);
    proxy_ = getDefaultInstance().getProxy();
  }
  /**
   * <code>optional string proxy = 6;</code>
   * @param value The bytes for proxy to set.
   */
  private void setProxyBytes(
      com.google.protobuf.ByteString value) {
    proxy_ = value.toStringUtf8();
    bitField0_ |= 0x00000010;
  }

  public static final int PORT_FIELD_NUMBER = 7;
  private java.lang.String port_;
  /**
   * <code>optional string port = 7;</code>
   * @return Whether the port field is set.
   */
  @java.lang.Override
  public boolean hasPort() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string port = 7;</code>
   * @return The port.
   */
  @java.lang.Override
  public java.lang.String getPort() {
    return port_;
  }
  /**
   * <code>optional string port = 7;</code>
   * @return The bytes for port.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPortBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(port_);
  }
  /**
   * <code>optional string port = 7;</code>
   * @param value The port to set.
   */
  private void setPort(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000020;
    port_ = value;
  }
  /**
   * <code>optional string port = 7;</code>
   */
  private void clearPort() {
    bitField0_ = (bitField0_ & ~0x00000020);
    port_ = getDefaultInstance().getPort();
  }
  /**
   * <code>optional string port = 7;</code>
   * @param value The bytes for port to set.
   */
  private void setPortBytes(
      com.google.protobuf.ByteString value) {
    port_ = value.toStringUtf8();
    bitField0_ |= 0x00000020;
  }

  public static final int USER_FIELD_NUMBER = 8;
  private java.lang.String user_;
  /**
   * <code>optional string user = 8;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string user = 8;</code>
   * @return The user.
   */
  @java.lang.Override
  public java.lang.String getUser() {
    return user_;
  }
  /**
   * <code>optional string user = 8;</code>
   * @return The bytes for user.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(user_);
  }
  /**
   * <code>optional string user = 8;</code>
   * @param value The user to set.
   */
  private void setUser(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000040;
    user_ = value;
  }
  /**
   * <code>optional string user = 8;</code>
   */
  private void clearUser() {
    bitField0_ = (bitField0_ & ~0x00000040);
    user_ = getDefaultInstance().getUser();
  }
  /**
   * <code>optional string user = 8;</code>
   * @param value The bytes for user to set.
   */
  private void setUserBytes(
      com.google.protobuf.ByteString value) {
    user_ = value.toStringUtf8();
    bitField0_ |= 0x00000040;
  }

  public static final int PASSWORD_FIELD_NUMBER = 9;
  private java.lang.String password_;
  /**
   * <code>optional string password = 9;</code>
   * @return Whether the password field is set.
   */
  @java.lang.Override
  public boolean hasPassword() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional string password = 9;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    return password_;
  }
  /**
   * <code>optional string password = 9;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(password_);
  }
  /**
   * <code>optional string password = 9;</code>
   * @param value The password to set.
   */
  private void setPassword(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000080;
    password_ = value;
  }
  /**
   * <code>optional string password = 9;</code>
   */
  private void clearPassword() {
    bitField0_ = (bitField0_ & ~0x00000080);
    password_ = getDefaultInstance().getPassword();
  }
  /**
   * <code>optional string password = 9;</code>
   * @param value The bytes for password to set.
   */
  private void setPasswordBytes(
      com.google.protobuf.ByteString value) {
    password_ = value.toStringUtf8();
    bitField0_ |= 0x00000080;
  }

  public static final int AUTHTYPE_FIELD_NUMBER = 10;
  private int authtype_;
  /**
   * <code>optional int32 authtype = 10;</code>
   * @return Whether the authtype field is set.
   */
  @java.lang.Override
  public boolean hasAuthtype() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional int32 authtype = 10;</code>
   * @return The authtype.
   */
  @java.lang.Override
  public int getAuthtype() {
    return authtype_;
  }
  /**
   * <code>optional int32 authtype = 10;</code>
   * @param value The authtype to set.
   */
  private void setAuthtype(int value) {
    bitField0_ |= 0x00000100;
    authtype_ = value;
  }
  /**
   * <code>optional int32 authtype = 10;</code>
   */
  private void clearAuthtype() {
    bitField0_ = (bitField0_ & ~0x00000100);
    authtype_ = 0;
  }

  public static final int MMSC_FIELD_NUMBER = 11;
  private java.lang.String mmsc_;
  /**
   * <code>optional string mmsc = 11;</code>
   * @return Whether the mmsc field is set.
   */
  @java.lang.Override
  public boolean hasMmsc() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional string mmsc = 11;</code>
   * @return The mmsc.
   */
  @java.lang.Override
  public java.lang.String getMmsc() {
    return mmsc_;
  }
  /**
   * <code>optional string mmsc = 11;</code>
   * @return The bytes for mmsc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMmscBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mmsc_);
  }
  /**
   * <code>optional string mmsc = 11;</code>
   * @param value The mmsc to set.
   */
  private void setMmsc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000200;
    mmsc_ = value;
  }
  /**
   * <code>optional string mmsc = 11;</code>
   */
  private void clearMmsc() {
    bitField0_ = (bitField0_ & ~0x00000200);
    mmsc_ = getDefaultInstance().getMmsc();
  }
  /**
   * <code>optional string mmsc = 11;</code>
   * @param value The bytes for mmsc to set.
   */
  private void setMmscBytes(
      com.google.protobuf.ByteString value) {
    mmsc_ = value.toStringUtf8();
    bitField0_ |= 0x00000200;
  }

  public static final int MMSCPROXY_FIELD_NUMBER = 12;
  private java.lang.String mmscProxy_;
  /**
   * <code>optional string mmscProxy = 12;</code>
   * @return Whether the mmscProxy field is set.
   */
  @java.lang.Override
  public boolean hasMmscProxy() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional string mmscProxy = 12;</code>
   * @return The mmscProxy.
   */
  @java.lang.Override
  public java.lang.String getMmscProxy() {
    return mmscProxy_;
  }
  /**
   * <code>optional string mmscProxy = 12;</code>
   * @return The bytes for mmscProxy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMmscProxyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mmscProxy_);
  }
  /**
   * <code>optional string mmscProxy = 12;</code>
   * @param value The mmscProxy to set.
   */
  private void setMmscProxy(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000400;
    mmscProxy_ = value;
  }
  /**
   * <code>optional string mmscProxy = 12;</code>
   */
  private void clearMmscProxy() {
    bitField0_ = (bitField0_ & ~0x00000400);
    mmscProxy_ = getDefaultInstance().getMmscProxy();
  }
  /**
   * <code>optional string mmscProxy = 12;</code>
   * @param value The bytes for mmscProxy to set.
   */
  private void setMmscProxyBytes(
      com.google.protobuf.ByteString value) {
    mmscProxy_ = value.toStringUtf8();
    bitField0_ |= 0x00000400;
  }

  public static final int MMSCPROXYPORT_FIELD_NUMBER = 13;
  private java.lang.String mmscProxyPort_;
  /**
   * <code>optional string mmscProxyPort = 13;</code>
   * @return Whether the mmscProxyPort field is set.
   */
  @java.lang.Override
  public boolean hasMmscProxyPort() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional string mmscProxyPort = 13;</code>
   * @return The mmscProxyPort.
   */
  @java.lang.Override
  public java.lang.String getMmscProxyPort() {
    return mmscProxyPort_;
  }
  /**
   * <code>optional string mmscProxyPort = 13;</code>
   * @return The bytes for mmscProxyPort.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMmscProxyPortBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mmscProxyPort_);
  }
  /**
   * <code>optional string mmscProxyPort = 13;</code>
   * @param value The mmscProxyPort to set.
   */
  private void setMmscProxyPort(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000800;
    mmscProxyPort_ = value;
  }
  /**
   * <code>optional string mmscProxyPort = 13;</code>
   */
  private void clearMmscProxyPort() {
    bitField0_ = (bitField0_ & ~0x00000800);
    mmscProxyPort_ = getDefaultInstance().getMmscProxyPort();
  }
  /**
   * <code>optional string mmscProxyPort = 13;</code>
   * @param value The bytes for mmscProxyPort to set.
   */
  private void setMmscProxyPortBytes(
      com.google.protobuf.ByteString value) {
    mmscProxyPort_ = value.toStringUtf8();
    bitField0_ |= 0x00000800;
  }

  public static final int PROTOCOL_FIELD_NUMBER = 14;
  private int protocol_;
  /**
   * <code>optional .ApnItem.Protocol protocol = 14;</code>
   * @return Whether the protocol field is set.
   */
  @java.lang.Override
  public boolean hasProtocol() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>optional .ApnItem.Protocol protocol = 14;</code>
   * @return The protocol.
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol getProtocol() {
    com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol result = com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol.forNumber(protocol_);
    return result == null ? com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol.IP : result;
  }
  /**
   * <code>optional .ApnItem.Protocol protocol = 14;</code>
   * @param value The protocol to set.
   */
  private void setProtocol(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol value) {
    protocol_ = value.getNumber();
    bitField0_ |= 0x00001000;
  }
  /**
   * <code>optional .ApnItem.Protocol protocol = 14;</code>
   */
  private void clearProtocol() {
    bitField0_ = (bitField0_ & ~0x00001000);
    protocol_ = 0;
  }

  public static final int ROAMINGPROTOCOL_FIELD_NUMBER = 15;
  private int roamingProtocol_;
  /**
   * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
   * @return Whether the roamingProtocol field is set.
   */
  @java.lang.Override
  public boolean hasRoamingProtocol() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
   * @return The roamingProtocol.
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol getRoamingProtocol() {
    com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol result = com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol.forNumber(roamingProtocol_);
    return result == null ? com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol.IP : result;
  }
  /**
   * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
   * @param value The roamingProtocol to set.
   */
  private void setRoamingProtocol(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol value) {
    roamingProtocol_ = value.getNumber();
    bitField0_ |= 0x00002000;
  }
  /**
   * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
   */
  private void clearRoamingProtocol() {
    bitField0_ = (bitField0_ & ~0x00002000);
    roamingProtocol_ = 0;
  }

  public static final int MTU_FIELD_NUMBER = 16;
  private int mtu_;
  /**
   * <code>optional int32 mtu = 16;</code>
   * @return Whether the mtu field is set.
   */
  @java.lang.Override
  public boolean hasMtu() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <code>optional int32 mtu = 16;</code>
   * @return The mtu.
   */
  @java.lang.Override
  public int getMtu() {
    return mtu_;
  }
  /**
   * <code>optional int32 mtu = 16;</code>
   * @param value The mtu to set.
   */
  private void setMtu(int value) {
    bitField0_ |= 0x00004000;
    mtu_ = value;
  }
  /**
   * <code>optional int32 mtu = 16;</code>
   */
  private void clearMtu() {
    bitField0_ = (bitField0_ & ~0x00004000);
    mtu_ = 0;
  }

  public static final int PROFILEID_FIELD_NUMBER = 17;
  private int profileId_;
  /**
   * <code>optional int32 profileId = 17;</code>
   * @return Whether the profileId field is set.
   */
  @java.lang.Override
  public boolean hasProfileId() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <code>optional int32 profileId = 17;</code>
   * @return The profileId.
   */
  @java.lang.Override
  public int getProfileId() {
    return profileId_;
  }
  /**
   * <code>optional int32 profileId = 17;</code>
   * @param value The profileId to set.
   */
  private void setProfileId(int value) {
    bitField0_ |= 0x00008000;
    profileId_ = value;
  }
  /**
   * <code>optional int32 profileId = 17;</code>
   */
  private void clearProfileId() {
    bitField0_ = (bitField0_ & ~0x00008000);
    profileId_ = 0;
  }

  public static final int MAXCONNS_FIELD_NUMBER = 18;
  private int maxConns_;
  /**
   * <code>optional int32 maxConns = 18;</code>
   * @return Whether the maxConns field is set.
   */
  @java.lang.Override
  public boolean hasMaxConns() {
    return ((bitField0_ & 0x00010000) != 0);
  }
  /**
   * <code>optional int32 maxConns = 18;</code>
   * @return The maxConns.
   */
  @java.lang.Override
  public int getMaxConns() {
    return maxConns_;
  }
  /**
   * <code>optional int32 maxConns = 18;</code>
   * @param value The maxConns to set.
   */
  private void setMaxConns(int value) {
    bitField0_ |= 0x00010000;
    maxConns_ = value;
  }
  /**
   * <code>optional int32 maxConns = 18;</code>
   */
  private void clearMaxConns() {
    bitField0_ = (bitField0_ & ~0x00010000);
    maxConns_ = 0;
  }

  public static final int WAITTIME_FIELD_NUMBER = 19;
  private int waitTime_;
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 waitTime = 19;</code>
   * @return Whether the waitTime field is set.
   */
  @java.lang.Override
  public boolean hasWaitTime() {
    return ((bitField0_ & 0x00020000) != 0);
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 waitTime = 19;</code>
   * @return The waitTime.
   */
  @java.lang.Override
  public int getWaitTime() {
    return waitTime_;
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 waitTime = 19;</code>
   * @param value The waitTime to set.
   */
  private void setWaitTime(int value) {
    bitField0_ |= 0x00020000;
    waitTime_ = value;
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 waitTime = 19;</code>
   */
  private void clearWaitTime() {
    bitField0_ = (bitField0_ & ~0x00020000);
    waitTime_ = 0;
  }

  public static final int MAXCONNSTIME_FIELD_NUMBER = 20;
  private int maxConnsTime_;
  /**
   * <code>optional int32 maxConnsTime = 20;</code>
   * @return Whether the maxConnsTime field is set.
   */
  @java.lang.Override
  public boolean hasMaxConnsTime() {
    return ((bitField0_ & 0x00040000) != 0);
  }
  /**
   * <code>optional int32 maxConnsTime = 20;</code>
   * @return The maxConnsTime.
   */
  @java.lang.Override
  public int getMaxConnsTime() {
    return maxConnsTime_;
  }
  /**
   * <code>optional int32 maxConnsTime = 20;</code>
   * @param value The maxConnsTime to set.
   */
  private void setMaxConnsTime(int value) {
    bitField0_ |= 0x00040000;
    maxConnsTime_ = value;
  }
  /**
   * <code>optional int32 maxConnsTime = 20;</code>
   */
  private void clearMaxConnsTime() {
    bitField0_ = (bitField0_ & ~0x00040000);
    maxConnsTime_ = 0;
  }

  public static final int CARRIERENABLED_FIELD_NUMBER = 21;
  private boolean carrierEnabled_;
  /**
   * <code>optional bool carrierEnabled = 21;</code>
   * @return Whether the carrierEnabled field is set.
   */
  @java.lang.Override
  public boolean hasCarrierEnabled() {
    return ((bitField0_ & 0x00080000) != 0);
  }
  /**
   * <code>optional bool carrierEnabled = 21;</code>
   * @return The carrierEnabled.
   */
  @java.lang.Override
  public boolean getCarrierEnabled() {
    return carrierEnabled_;
  }
  /**
   * <code>optional bool carrierEnabled = 21;</code>
   * @param value The carrierEnabled to set.
   */
  private void setCarrierEnabled(boolean value) {
    bitField0_ |= 0x00080000;
    carrierEnabled_ = value;
  }
  /**
   * <code>optional bool carrierEnabled = 21;</code>
   */
  private void clearCarrierEnabled() {
    bitField0_ = (bitField0_ & ~0x00080000);
    carrierEnabled_ = false;
  }

  public static final int MODEMCOGNITIVE_FIELD_NUMBER = 22;
  private boolean modemCognitive_;
  /**
   * <code>optional bool modemCognitive = 22;</code>
   * @return Whether the modemCognitive field is set.
   */
  @java.lang.Override
  public boolean hasModemCognitive() {
    return ((bitField0_ & 0x00100000) != 0);
  }
  /**
   * <code>optional bool modemCognitive = 22;</code>
   * @return The modemCognitive.
   */
  @java.lang.Override
  public boolean getModemCognitive() {
    return modemCognitive_;
  }
  /**
   * <code>optional bool modemCognitive = 22;</code>
   * @param value The modemCognitive to set.
   */
  private void setModemCognitive(boolean value) {
    bitField0_ |= 0x00100000;
    modemCognitive_ = value;
  }
  /**
   * <code>optional bool modemCognitive = 22;</code>
   */
  private void clearModemCognitive() {
    bitField0_ = (bitField0_ & ~0x00100000);
    modemCognitive_ = false;
  }

  public static final int USERVISIBLE_FIELD_NUMBER = 23;
  private boolean userVisible_;
  /**
   * <code>optional bool userVisible = 23;</code>
   * @return Whether the userVisible field is set.
   */
  @java.lang.Override
  public boolean hasUserVisible() {
    return ((bitField0_ & 0x00200000) != 0);
  }
  /**
   * <code>optional bool userVisible = 23;</code>
   * @return The userVisible.
   */
  @java.lang.Override
  public boolean getUserVisible() {
    return userVisible_;
  }
  /**
   * <code>optional bool userVisible = 23;</code>
   * @param value The userVisible to set.
   */
  private void setUserVisible(boolean value) {
    bitField0_ |= 0x00200000;
    userVisible_ = value;
  }
  /**
   * <code>optional bool userVisible = 23;</code>
   */
  private void clearUserVisible() {
    bitField0_ = (bitField0_ & ~0x00200000);
    userVisible_ = false;
  }

  public static final int USEREDITABLE_FIELD_NUMBER = 24;
  private boolean userEditable_;
  /**
   * <code>optional bool userEditable = 24;</code>
   * @return Whether the userEditable field is set.
   */
  @java.lang.Override
  public boolean hasUserEditable() {
    return ((bitField0_ & 0x00400000) != 0);
  }
  /**
   * <code>optional bool userEditable = 24;</code>
   * @return The userEditable.
   */
  @java.lang.Override
  public boolean getUserEditable() {
    return userEditable_;
  }
  /**
   * <code>optional bool userEditable = 24;</code>
   * @param value The userEditable to set.
   */
  private void setUserEditable(boolean value) {
    bitField0_ |= 0x00400000;
    userEditable_ = value;
  }
  /**
   * <code>optional bool userEditable = 24;</code>
   */
  private void clearUserEditable() {
    bitField0_ = (bitField0_ & ~0x00400000);
    userEditable_ = false;
  }

  public static final int APNSETID_FIELD_NUMBER = 25;
  private int apnSetId_;
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 apnSetId = 25;</code>
   * @return Whether the apnSetId field is set.
   */
  @java.lang.Override
  public boolean hasApnSetId() {
    return ((bitField0_ & 0x00800000) != 0);
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 apnSetId = 25;</code>
   * @return The apnSetId.
   */
  @java.lang.Override
  public int getApnSetId() {
    return apnSetId_;
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 apnSetId = 25;</code>
   * @param value The apnSetId to set.
   */
  private void setApnSetId(int value) {
    bitField0_ |= 0x00800000;
    apnSetId_ = value;
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional int32 apnSetId = 25;</code>
   */
  private void clearApnSetId() {
    bitField0_ = (bitField0_ & ~0x00800000);
    apnSetId_ = 0;
  }

  public static final int SKIP464XLAT_FIELD_NUMBER = 26;
  private int skip464Xlat_;
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
   * @return Whether the skip464Xlat field is set.
   */
  @java.lang.Override
  public boolean hasSkip464Xlat() {
    return ((bitField0_ & 0x01000000) != 0);
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
   * @return The skip464Xlat.
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat getSkip464Xlat() {
    com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat result = com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat.forNumber(skip464Xlat_);
    return result == null ? com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat.SKIP_464XLAT_DEFAULT : result;
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
   * @param value The skip464Xlat to set.
   */
  private void setSkip464Xlat(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat value) {
    skip464Xlat_ = value.getNumber();
    bitField0_ |= 0x01000000;
  }
  /**
   * <pre>
   * unused
   * </pre>
   *
   * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
   */
  private void clearSkip464Xlat() {
    bitField0_ = (bitField0_ & ~0x01000000);
    skip464Xlat_ = 0;
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.ApnItem prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ApnItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.ApnItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:ApnItem)
      com.nooriro.oneuplus.proto.googlecarrier.ApnItemOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.ApnItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return instance.hasName();
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>required string value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return instance.hasValue();
    }
    /**
     * <code>required string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <code>required string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <code>required string value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <code>required string value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <code>required string value = 2;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @return A list containing the type.
     */
    @java.lang.Override
    public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType> getTypeList() {
      return instance.getTypeList();
    }
    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @return The count of type.
     */
    @java.lang.Override
    public int getTypeCount() {
      return instance.getTypeCount();
    }
    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @param index The index of the element to return.
     * @return The type at the given index.
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType getType(int index) {
      return instance.getType(index);
    }
    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @param index The index to set the value at.
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType value) {
      copyOnWrite();
      instance.setType(index, value);
      return this;
    }
    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @param value The type to add.
     * @return This builder for chaining.
     */
    public Builder addType(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType value) {
      copyOnWrite();
      instance.addType(value);
      return this;
    }
    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @param values The type to add.
     * @return This builder for chaining.
     */
    public Builder addAllType(
        java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType> values) {
      copyOnWrite();
      instance.addAllType(values);  return this;
    }
    /**
     * <code>repeated .ApnItem.ApnType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }

    /**
     * <code>optional string bearerBitmask = 4;</code>
     * @return Whether the bearerBitmask field is set.
     */
    @java.lang.Override
    public boolean hasBearerBitmask() {
      return instance.hasBearerBitmask();
    }
    /**
     * <code>optional string bearerBitmask = 4;</code>
     * @return The bearerBitmask.
     */
    @java.lang.Override
    public java.lang.String getBearerBitmask() {
      return instance.getBearerBitmask();
    }
    /**
     * <code>optional string bearerBitmask = 4;</code>
     * @return The bytes for bearerBitmask.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBearerBitmaskBytes() {
      return instance.getBearerBitmaskBytes();
    }
    /**
     * <code>optional string bearerBitmask = 4;</code>
     * @param value The bearerBitmask to set.
     * @return This builder for chaining.
     */
    public Builder setBearerBitmask(
        java.lang.String value) {
      copyOnWrite();
      instance.setBearerBitmask(value);
      return this;
    }
    /**
     * <code>optional string bearerBitmask = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBearerBitmask() {
      copyOnWrite();
      instance.clearBearerBitmask();
      return this;
    }
    /**
     * <code>optional string bearerBitmask = 4;</code>
     * @param value The bytes for bearerBitmask to set.
     * @return This builder for chaining.
     */
    public Builder setBearerBitmaskBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBearerBitmaskBytes(value);
      return this;
    }

    /**
     * <code>optional string server = 5;</code>
     * @return Whether the server field is set.
     */
    @java.lang.Override
    public boolean hasServer() {
      return instance.hasServer();
    }
    /**
     * <code>optional string server = 5;</code>
     * @return The server.
     */
    @java.lang.Override
    public java.lang.String getServer() {
      return instance.getServer();
    }
    /**
     * <code>optional string server = 5;</code>
     * @return The bytes for server.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerBytes() {
      return instance.getServerBytes();
    }
    /**
     * <code>optional string server = 5;</code>
     * @param value The server to set.
     * @return This builder for chaining.
     */
    public Builder setServer(
        java.lang.String value) {
      copyOnWrite();
      instance.setServer(value);
      return this;
    }
    /**
     * <code>optional string server = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearServer() {
      copyOnWrite();
      instance.clearServer();
      return this;
    }
    /**
     * <code>optional string server = 5;</code>
     * @param value The bytes for server to set.
     * @return This builder for chaining.
     */
    public Builder setServerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerBytes(value);
      return this;
    }

    /**
     * <code>optional string proxy = 6;</code>
     * @return Whether the proxy field is set.
     */
    @java.lang.Override
    public boolean hasProxy() {
      return instance.hasProxy();
    }
    /**
     * <code>optional string proxy = 6;</code>
     * @return The proxy.
     */
    @java.lang.Override
    public java.lang.String getProxy() {
      return instance.getProxy();
    }
    /**
     * <code>optional string proxy = 6;</code>
     * @return The bytes for proxy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProxyBytes() {
      return instance.getProxyBytes();
    }
    /**
     * <code>optional string proxy = 6;</code>
     * @param value The proxy to set.
     * @return This builder for chaining.
     */
    public Builder setProxy(
        java.lang.String value) {
      copyOnWrite();
      instance.setProxy(value);
      return this;
    }
    /**
     * <code>optional string proxy = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProxy() {
      copyOnWrite();
      instance.clearProxy();
      return this;
    }
    /**
     * <code>optional string proxy = 6;</code>
     * @param value The bytes for proxy to set.
     * @return This builder for chaining.
     */
    public Builder setProxyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProxyBytes(value);
      return this;
    }

    /**
     * <code>optional string port = 7;</code>
     * @return Whether the port field is set.
     */
    @java.lang.Override
    public boolean hasPort() {
      return instance.hasPort();
    }
    /**
     * <code>optional string port = 7;</code>
     * @return The port.
     */
    @java.lang.Override
    public java.lang.String getPort() {
      return instance.getPort();
    }
    /**
     * <code>optional string port = 7;</code>
     * @return The bytes for port.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPortBytes() {
      return instance.getPortBytes();
    }
    /**
     * <code>optional string port = 7;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(
        java.lang.String value) {
      copyOnWrite();
      instance.setPort(value);
      return this;
    }
    /**
     * <code>optional string port = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      copyOnWrite();
      instance.clearPort();
      return this;
    }
    /**
     * <code>optional string port = 7;</code>
     * @param value The bytes for port to set.
     * @return This builder for chaining.
     */
    public Builder setPortBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPortBytes(value);
      return this;
    }

    /**
     * <code>optional string user = 8;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return instance.hasUser();
    }
    /**
     * <code>optional string user = 8;</code>
     * @return The user.
     */
    @java.lang.Override
    public java.lang.String getUser() {
      return instance.getUser();
    }
    /**
     * <code>optional string user = 8;</code>
     * @return The bytes for user.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserBytes() {
      return instance.getUserBytes();
    }
    /**
     * <code>optional string user = 8;</code>
     * @param value The user to set.
     * @return This builder for chaining.
     */
    public Builder setUser(
        java.lang.String value) {
      copyOnWrite();
      instance.setUser(value);
      return this;
    }
    /**
     * <code>optional string user = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUser() {
      copyOnWrite();
      instance.clearUser();
      return this;
    }
    /**
     * <code>optional string user = 8;</code>
     * @param value The bytes for user to set.
     * @return This builder for chaining.
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserBytes(value);
      return this;
    }

    /**
     * <code>optional string password = 9;</code>
     * @return Whether the password field is set.
     */
    @java.lang.Override
    public boolean hasPassword() {
      return instance.hasPassword();
    }
    /**
     * <code>optional string password = 9;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      return instance.getPassword();
    }
    /**
     * <code>optional string password = 9;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return instance.getPasswordBytes();
    }
    /**
     * <code>optional string password = 9;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      copyOnWrite();
      instance.setPassword(value);
      return this;
    }
    /**
     * <code>optional string password = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      copyOnWrite();
      instance.clearPassword();
      return this;
    }
    /**
     * <code>optional string password = 9;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPasswordBytes(value);
      return this;
    }

    /**
     * <code>optional int32 authtype = 10;</code>
     * @return Whether the authtype field is set.
     */
    @java.lang.Override
    public boolean hasAuthtype() {
      return instance.hasAuthtype();
    }
    /**
     * <code>optional int32 authtype = 10;</code>
     * @return The authtype.
     */
    @java.lang.Override
    public int getAuthtype() {
      return instance.getAuthtype();
    }
    /**
     * <code>optional int32 authtype = 10;</code>
     * @param value The authtype to set.
     * @return This builder for chaining.
     */
    public Builder setAuthtype(int value) {
      copyOnWrite();
      instance.setAuthtype(value);
      return this;
    }
    /**
     * <code>optional int32 authtype = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthtype() {
      copyOnWrite();
      instance.clearAuthtype();
      return this;
    }

    /**
     * <code>optional string mmsc = 11;</code>
     * @return Whether the mmsc field is set.
     */
    @java.lang.Override
    public boolean hasMmsc() {
      return instance.hasMmsc();
    }
    /**
     * <code>optional string mmsc = 11;</code>
     * @return The mmsc.
     */
    @java.lang.Override
    public java.lang.String getMmsc() {
      return instance.getMmsc();
    }
    /**
     * <code>optional string mmsc = 11;</code>
     * @return The bytes for mmsc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMmscBytes() {
      return instance.getMmscBytes();
    }
    /**
     * <code>optional string mmsc = 11;</code>
     * @param value The mmsc to set.
     * @return This builder for chaining.
     */
    public Builder setMmsc(
        java.lang.String value) {
      copyOnWrite();
      instance.setMmsc(value);
      return this;
    }
    /**
     * <code>optional string mmsc = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMmsc() {
      copyOnWrite();
      instance.clearMmsc();
      return this;
    }
    /**
     * <code>optional string mmsc = 11;</code>
     * @param value The bytes for mmsc to set.
     * @return This builder for chaining.
     */
    public Builder setMmscBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMmscBytes(value);
      return this;
    }

    /**
     * <code>optional string mmscProxy = 12;</code>
     * @return Whether the mmscProxy field is set.
     */
    @java.lang.Override
    public boolean hasMmscProxy() {
      return instance.hasMmscProxy();
    }
    /**
     * <code>optional string mmscProxy = 12;</code>
     * @return The mmscProxy.
     */
    @java.lang.Override
    public java.lang.String getMmscProxy() {
      return instance.getMmscProxy();
    }
    /**
     * <code>optional string mmscProxy = 12;</code>
     * @return The bytes for mmscProxy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMmscProxyBytes() {
      return instance.getMmscProxyBytes();
    }
    /**
     * <code>optional string mmscProxy = 12;</code>
     * @param value The mmscProxy to set.
     * @return This builder for chaining.
     */
    public Builder setMmscProxy(
        java.lang.String value) {
      copyOnWrite();
      instance.setMmscProxy(value);
      return this;
    }
    /**
     * <code>optional string mmscProxy = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMmscProxy() {
      copyOnWrite();
      instance.clearMmscProxy();
      return this;
    }
    /**
     * <code>optional string mmscProxy = 12;</code>
     * @param value The bytes for mmscProxy to set.
     * @return This builder for chaining.
     */
    public Builder setMmscProxyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMmscProxyBytes(value);
      return this;
    }

    /**
     * <code>optional string mmscProxyPort = 13;</code>
     * @return Whether the mmscProxyPort field is set.
     */
    @java.lang.Override
    public boolean hasMmscProxyPort() {
      return instance.hasMmscProxyPort();
    }
    /**
     * <code>optional string mmscProxyPort = 13;</code>
     * @return The mmscProxyPort.
     */
    @java.lang.Override
    public java.lang.String getMmscProxyPort() {
      return instance.getMmscProxyPort();
    }
    /**
     * <code>optional string mmscProxyPort = 13;</code>
     * @return The bytes for mmscProxyPort.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMmscProxyPortBytes() {
      return instance.getMmscProxyPortBytes();
    }
    /**
     * <code>optional string mmscProxyPort = 13;</code>
     * @param value The mmscProxyPort to set.
     * @return This builder for chaining.
     */
    public Builder setMmscProxyPort(
        java.lang.String value) {
      copyOnWrite();
      instance.setMmscProxyPort(value);
      return this;
    }
    /**
     * <code>optional string mmscProxyPort = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMmscProxyPort() {
      copyOnWrite();
      instance.clearMmscProxyPort();
      return this;
    }
    /**
     * <code>optional string mmscProxyPort = 13;</code>
     * @param value The bytes for mmscProxyPort to set.
     * @return This builder for chaining.
     */
    public Builder setMmscProxyPortBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMmscProxyPortBytes(value);
      return this;
    }

    /**
     * <code>optional .ApnItem.Protocol protocol = 14;</code>
     * @return Whether the protocol field is set.
     */
    @java.lang.Override
    public boolean hasProtocol() {
      return instance.hasProtocol();
    }
    /**
     * <code>optional .ApnItem.Protocol protocol = 14;</code>
     * @return The protocol.
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol getProtocol() {
      return instance.getProtocol();
    }
    /**
     * <code>optional .ApnItem.Protocol protocol = 14;</code>
     * @param value The enum numeric value on the wire for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol value) {
      copyOnWrite();
      instance.setProtocol(value);
      return this;
    }
    /**
     * <code>optional .ApnItem.Protocol protocol = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      copyOnWrite();
      instance.clearProtocol();
      return this;
    }

    /**
     * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
     * @return Whether the roamingProtocol field is set.
     */
    @java.lang.Override
    public boolean hasRoamingProtocol() {
      return instance.hasRoamingProtocol();
    }
    /**
     * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
     * @return The roamingProtocol.
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol getRoamingProtocol() {
      return instance.getRoamingProtocol();
    }
    /**
     * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
     * @param value The enum numeric value on the wire for roamingProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setRoamingProtocol(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol value) {
      copyOnWrite();
      instance.setRoamingProtocol(value);
      return this;
    }
    /**
     * <code>optional .ApnItem.Protocol roamingProtocol = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoamingProtocol() {
      copyOnWrite();
      instance.clearRoamingProtocol();
      return this;
    }

    /**
     * <code>optional int32 mtu = 16;</code>
     * @return Whether the mtu field is set.
     */
    @java.lang.Override
    public boolean hasMtu() {
      return instance.hasMtu();
    }
    /**
     * <code>optional int32 mtu = 16;</code>
     * @return The mtu.
     */
    @java.lang.Override
    public int getMtu() {
      return instance.getMtu();
    }
    /**
     * <code>optional int32 mtu = 16;</code>
     * @param value The mtu to set.
     * @return This builder for chaining.
     */
    public Builder setMtu(int value) {
      copyOnWrite();
      instance.setMtu(value);
      return this;
    }
    /**
     * <code>optional int32 mtu = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearMtu() {
      copyOnWrite();
      instance.clearMtu();
      return this;
    }

    /**
     * <code>optional int32 profileId = 17;</code>
     * @return Whether the profileId field is set.
     */
    @java.lang.Override
    public boolean hasProfileId() {
      return instance.hasProfileId();
    }
    /**
     * <code>optional int32 profileId = 17;</code>
     * @return The profileId.
     */
    @java.lang.Override
    public int getProfileId() {
      return instance.getProfileId();
    }
    /**
     * <code>optional int32 profileId = 17;</code>
     * @param value The profileId to set.
     * @return This builder for chaining.
     */
    public Builder setProfileId(int value) {
      copyOnWrite();
      instance.setProfileId(value);
      return this;
    }
    /**
     * <code>optional int32 profileId = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfileId() {
      copyOnWrite();
      instance.clearProfileId();
      return this;
    }

    /**
     * <code>optional int32 maxConns = 18;</code>
     * @return Whether the maxConns field is set.
     */
    @java.lang.Override
    public boolean hasMaxConns() {
      return instance.hasMaxConns();
    }
    /**
     * <code>optional int32 maxConns = 18;</code>
     * @return The maxConns.
     */
    @java.lang.Override
    public int getMaxConns() {
      return instance.getMaxConns();
    }
    /**
     * <code>optional int32 maxConns = 18;</code>
     * @param value The maxConns to set.
     * @return This builder for chaining.
     */
    public Builder setMaxConns(int value) {
      copyOnWrite();
      instance.setMaxConns(value);
      return this;
    }
    /**
     * <code>optional int32 maxConns = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxConns() {
      copyOnWrite();
      instance.clearMaxConns();
      return this;
    }

    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 waitTime = 19;</code>
     * @return Whether the waitTime field is set.
     */
    @java.lang.Override
    public boolean hasWaitTime() {
      return instance.hasWaitTime();
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 waitTime = 19;</code>
     * @return The waitTime.
     */
    @java.lang.Override
    public int getWaitTime() {
      return instance.getWaitTime();
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 waitTime = 19;</code>
     * @param value The waitTime to set.
     * @return This builder for chaining.
     */
    public Builder setWaitTime(int value) {
      copyOnWrite();
      instance.setWaitTime(value);
      return this;
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 waitTime = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaitTime() {
      copyOnWrite();
      instance.clearWaitTime();
      return this;
    }

    /**
     * <code>optional int32 maxConnsTime = 20;</code>
     * @return Whether the maxConnsTime field is set.
     */
    @java.lang.Override
    public boolean hasMaxConnsTime() {
      return instance.hasMaxConnsTime();
    }
    /**
     * <code>optional int32 maxConnsTime = 20;</code>
     * @return The maxConnsTime.
     */
    @java.lang.Override
    public int getMaxConnsTime() {
      return instance.getMaxConnsTime();
    }
    /**
     * <code>optional int32 maxConnsTime = 20;</code>
     * @param value The maxConnsTime to set.
     * @return This builder for chaining.
     */
    public Builder setMaxConnsTime(int value) {
      copyOnWrite();
      instance.setMaxConnsTime(value);
      return this;
    }
    /**
     * <code>optional int32 maxConnsTime = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxConnsTime() {
      copyOnWrite();
      instance.clearMaxConnsTime();
      return this;
    }

    /**
     * <code>optional bool carrierEnabled = 21;</code>
     * @return Whether the carrierEnabled field is set.
     */
    @java.lang.Override
    public boolean hasCarrierEnabled() {
      return instance.hasCarrierEnabled();
    }
    /**
     * <code>optional bool carrierEnabled = 21;</code>
     * @return The carrierEnabled.
     */
    @java.lang.Override
    public boolean getCarrierEnabled() {
      return instance.getCarrierEnabled();
    }
    /**
     * <code>optional bool carrierEnabled = 21;</code>
     * @param value The carrierEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setCarrierEnabled(boolean value) {
      copyOnWrite();
      instance.setCarrierEnabled(value);
      return this;
    }
    /**
     * <code>optional bool carrierEnabled = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearCarrierEnabled() {
      copyOnWrite();
      instance.clearCarrierEnabled();
      return this;
    }

    /**
     * <code>optional bool modemCognitive = 22;</code>
     * @return Whether the modemCognitive field is set.
     */
    @java.lang.Override
    public boolean hasModemCognitive() {
      return instance.hasModemCognitive();
    }
    /**
     * <code>optional bool modemCognitive = 22;</code>
     * @return The modemCognitive.
     */
    @java.lang.Override
    public boolean getModemCognitive() {
      return instance.getModemCognitive();
    }
    /**
     * <code>optional bool modemCognitive = 22;</code>
     * @param value The modemCognitive to set.
     * @return This builder for chaining.
     */
    public Builder setModemCognitive(boolean value) {
      copyOnWrite();
      instance.setModemCognitive(value);
      return this;
    }
    /**
     * <code>optional bool modemCognitive = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearModemCognitive() {
      copyOnWrite();
      instance.clearModemCognitive();
      return this;
    }

    /**
     * <code>optional bool userVisible = 23;</code>
     * @return Whether the userVisible field is set.
     */
    @java.lang.Override
    public boolean hasUserVisible() {
      return instance.hasUserVisible();
    }
    /**
     * <code>optional bool userVisible = 23;</code>
     * @return The userVisible.
     */
    @java.lang.Override
    public boolean getUserVisible() {
      return instance.getUserVisible();
    }
    /**
     * <code>optional bool userVisible = 23;</code>
     * @param value The userVisible to set.
     * @return This builder for chaining.
     */
    public Builder setUserVisible(boolean value) {
      copyOnWrite();
      instance.setUserVisible(value);
      return this;
    }
    /**
     * <code>optional bool userVisible = 23;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserVisible() {
      copyOnWrite();
      instance.clearUserVisible();
      return this;
    }

    /**
     * <code>optional bool userEditable = 24;</code>
     * @return Whether the userEditable field is set.
     */
    @java.lang.Override
    public boolean hasUserEditable() {
      return instance.hasUserEditable();
    }
    /**
     * <code>optional bool userEditable = 24;</code>
     * @return The userEditable.
     */
    @java.lang.Override
    public boolean getUserEditable() {
      return instance.getUserEditable();
    }
    /**
     * <code>optional bool userEditable = 24;</code>
     * @param value The userEditable to set.
     * @return This builder for chaining.
     */
    public Builder setUserEditable(boolean value) {
      copyOnWrite();
      instance.setUserEditable(value);
      return this;
    }
    /**
     * <code>optional bool userEditable = 24;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserEditable() {
      copyOnWrite();
      instance.clearUserEditable();
      return this;
    }

    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 apnSetId = 25;</code>
     * @return Whether the apnSetId field is set.
     */
    @java.lang.Override
    public boolean hasApnSetId() {
      return instance.hasApnSetId();
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 apnSetId = 25;</code>
     * @return The apnSetId.
     */
    @java.lang.Override
    public int getApnSetId() {
      return instance.getApnSetId();
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 apnSetId = 25;</code>
     * @param value The apnSetId to set.
     * @return This builder for chaining.
     */
    public Builder setApnSetId(int value) {
      copyOnWrite();
      instance.setApnSetId(value);
      return this;
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional int32 apnSetId = 25;</code>
     * @return This builder for chaining.
     */
    public Builder clearApnSetId() {
      copyOnWrite();
      instance.clearApnSetId();
      return this;
    }

    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
     * @return Whether the skip464Xlat field is set.
     */
    @java.lang.Override
    public boolean hasSkip464Xlat() {
      return instance.hasSkip464Xlat();
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
     * @return The skip464Xlat.
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat getSkip464Xlat() {
      return instance.getSkip464Xlat();
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
     * @param value The enum numeric value on the wire for skip464Xlat to set.
     * @return This builder for chaining.
     */
    public Builder setSkip464Xlat(com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat value) {
      copyOnWrite();
      instance.setSkip464Xlat(value);
      return this;
    }
    /**
     * <pre>
     * unused
     * </pre>
     *
     * <code>optional .ApnItem.Xlat skip464Xlat = 26;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkip464Xlat() {
      copyOnWrite();
      instance.clearSkip464Xlat();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ApnItem)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.ApnItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "name_",
            "value_",
            "type_",
            com.nooriro.oneuplus.proto.googlecarrier.ApnItem.ApnType.internalGetVerifier(),
            "bearerBitmask_",
            "server_",
            "proxy_",
            "port_",
            "user_",
            "password_",
            "authtype_",
            "mmsc_",
            "mmscProxy_",
            "mmscProxyPort_",
            "protocol_",
            com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol.internalGetVerifier(),
            "roamingProtocol_",
            com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Protocol.internalGetVerifier(),
            "mtu_",
            "profileId_",
            "maxConns_",
            "waitTime_",
            "maxConnsTime_",
            "carrierEnabled_",
            "modemCognitive_",
            "userVisible_",
            "userEditable_",
            "apnSetId_",
            "skip464Xlat_",
            com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Xlat.internalGetVerifier(),
          };
          java.lang.String info =
              "\u0001\u001a\u0000\u0001\u0001\u001a\u001a\u0000\u0001\u0001\u0001\u1008\u0000\u0002" +
              "\u1508\u0001\u0003\u001e\u0004\u1008\u0002\u0005\u1008\u0003\u0006\u1008\u0004\u0007" +
              "\u1008\u0005\b\u1008\u0006\t\u1008\u0007\n\u1004\b\u000b\u1008\t\f\u1008\n\r\u1008" +
              "\u000b\u000e\u100c\f\u000f\u100c\r\u0010\u1004\u000e\u0011\u1004\u000f\u0012\u1004" +
              "\u0010\u0013\u1004\u0011\u0014\u1004\u0012\u0015\u1007\u0013\u0016\u1007\u0014\u0017" +
              "\u1007\u0015\u0018\u1007\u0016\u0019\u1004\u0017\u001a\u100c\u0018";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.ApnItem> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.ApnItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.ApnItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ApnItem)
  private static final com.nooriro.oneuplus.proto.googlecarrier.ApnItem DEFAULT_INSTANCE;
  static {
    ApnItem defaultInstance = new ApnItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ApnItem.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.ApnItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ApnItem> PARSER;

  public static com.google.protobuf.Parser<ApnItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

