// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code CarrierSettings}
 */
public  final class CarrierSettings extends
    com.google.protobuf.GeneratedMessageLite<
        CarrierSettings, CarrierSettings.Builder> implements
    // @@protoc_insertion_point(message_implements:CarrierSettings)
    CarrierSettingsOrBuilder {
  private CarrierSettings() {
    canonicalName_ = "";
  }
  private int bitField0_;
  public static final int CANONICALNAME_FIELD_NUMBER = 1;
  private java.lang.String canonicalName_;
  /**
   * <pre>
   * unique key
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return Whether the canonicalName field is set.
   */
  @java.lang.Override
  public boolean hasCanonicalName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * unique key
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return The canonicalName.
   */
  @java.lang.Override
  public java.lang.String getCanonicalName() {
    return canonicalName_;
  }
  /**
   * <pre>
   * unique key
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return The bytes for canonicalName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCanonicalNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(canonicalName_);
  }
  /**
   * <pre>
   * unique key
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @param value The canonicalName to set.
   */
  private void setCanonicalName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    canonicalName_ = value;
  }
  /**
   * <pre>
   * unique key
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   */
  private void clearCanonicalName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    canonicalName_ = getDefaultInstance().getCanonicalName();
  }
  /**
   * <pre>
   * unique key
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @param value The bytes for canonicalName to set.
   */
  private void setCanonicalNameBytes(
      com.google.protobuf.ByteString value) {
    canonicalName_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private long version_;
  /**
   * <code>optional int64 version = 2;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }
  /**
   * <code>optional int64 version = 2;</code>
   * @param value The version to set.
   */
  private void setVersion(long value) {
    bitField0_ |= 0x00000002;
    version_ = value;
  }
  /**
   * <code>optional int64 version = 2;</code>
   */
  private void clearVersion() {
    bitField0_ = (bitField0_ & ~0x00000002);
    version_ = 0L;
  }

  public static final int APNS_FIELD_NUMBER = 3;
  private com.nooriro.oneuplus.proto.googlecarrier.CarrierApns apns_;
  /**
   * <code>optional .CarrierApns apns = 3;</code>
   */
  @java.lang.Override
  public boolean hasApns() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .CarrierApns apns = 3;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierApns getApns() {
    return apns_ == null ? com.nooriro.oneuplus.proto.googlecarrier.CarrierApns.getDefaultInstance() : apns_;
  }
  /**
   * <code>optional .CarrierApns apns = 3;</code>
   */
  private void setApns(com.nooriro.oneuplus.proto.googlecarrier.CarrierApns value) {
    value.getClass();
  apns_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>optional .CarrierApns apns = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeApns(com.nooriro.oneuplus.proto.googlecarrier.CarrierApns value) {
    value.getClass();
  if (apns_ != null &&
        apns_ != com.nooriro.oneuplus.proto.googlecarrier.CarrierApns.getDefaultInstance()) {
      apns_ =
        com.nooriro.oneuplus.proto.googlecarrier.CarrierApns.newBuilder(apns_).mergeFrom(value).buildPartial();
    } else {
      apns_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .CarrierApns apns = 3;</code>
   */
  private void clearApns() {  apns_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int CONFIGS_FIELD_NUMBER = 4;
  private com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig configs_;
  /**
   * <code>optional .CarrierConfig configs = 4;</code>
   */
  @java.lang.Override
  public boolean hasConfigs() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .CarrierConfig configs = 4;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig getConfigs() {
    return configs_ == null ? com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig.getDefaultInstance() : configs_;
  }
  /**
   * <code>optional .CarrierConfig configs = 4;</code>
   */
  private void setConfigs(com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig value) {
    value.getClass();
  configs_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <code>optional .CarrierConfig configs = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeConfigs(com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig value) {
    value.getClass();
  if (configs_ != null &&
        configs_ != com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig.getDefaultInstance()) {
      configs_ =
        com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig.newBuilder(configs_).mergeFrom(value).buildPartial();
    } else {
      configs_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .CarrierConfig configs = 4;</code>
   */
  private void clearConfigs() {  configs_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int VENDORCONFIGS_FIELD_NUMBER = 5;
  private com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs vendorConfigs_;
  /**
   * <code>optional .VendorConfigs vendorConfigs = 5;</code>
   */
  @java.lang.Override
  public boolean hasVendorConfigs() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .VendorConfigs vendorConfigs = 5;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs getVendorConfigs() {
    return vendorConfigs_ == null ? com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs.getDefaultInstance() : vendorConfigs_;
  }
  /**
   * <code>optional .VendorConfigs vendorConfigs = 5;</code>
   */
  private void setVendorConfigs(com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs value) {
    value.getClass();
  vendorConfigs_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <code>optional .VendorConfigs vendorConfigs = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVendorConfigs(com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs value) {
    value.getClass();
  if (vendorConfigs_ != null &&
        vendorConfigs_ != com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs.getDefaultInstance()) {
      vendorConfigs_ =
        com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs.newBuilder(vendorConfigs_).mergeFrom(value).buildPartial();
    } else {
      vendorConfigs_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .VendorConfigs vendorConfigs = 5;</code>
   */
  private void clearVendorConfigs() {  vendorConfigs_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CarrierSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings, Builder> implements
      // @@protoc_insertion_point(builder_implements:CarrierSettings)
      com.nooriro.oneuplus.proto.googlecarrier.CarrierSettingsOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * unique key
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return Whether the canonicalName field is set.
     */
    @java.lang.Override
    public boolean hasCanonicalName() {
      return instance.hasCanonicalName();
    }
    /**
     * <pre>
     * unique key
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return The canonicalName.
     */
    @java.lang.Override
    public java.lang.String getCanonicalName() {
      return instance.getCanonicalName();
    }
    /**
     * <pre>
     * unique key
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return The bytes for canonicalName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCanonicalNameBytes() {
      return instance.getCanonicalNameBytes();
    }
    /**
     * <pre>
     * unique key
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @param value The canonicalName to set.
     * @return This builder for chaining.
     */
    public Builder setCanonicalName(
        java.lang.String value) {
      copyOnWrite();
      instance.setCanonicalName(value);
      return this;
    }
    /**
     * <pre>
     * unique key
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanonicalName() {
      copyOnWrite();
      instance.clearCanonicalName();
      return this;
    }
    /**
     * <pre>
     * unique key
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @param value The bytes for canonicalName to set.
     * @return This builder for chaining.
     */
    public Builder setCanonicalNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCanonicalNameBytes(value);
      return this;
    }

    /**
     * <code>optional int64 version = 2;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <code>optional int64 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>optional int64 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>optional int64 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>optional .CarrierApns apns = 3;</code>
     */
    @java.lang.Override
    public boolean hasApns() {
      return instance.hasApns();
    }
    /**
     * <code>optional .CarrierApns apns = 3;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.CarrierApns getApns() {
      return instance.getApns();
    }
    /**
     * <code>optional .CarrierApns apns = 3;</code>
     */
    public Builder setApns(com.nooriro.oneuplus.proto.googlecarrier.CarrierApns value) {
      copyOnWrite();
      instance.setApns(value);
      return this;
      }
    /**
     * <code>optional .CarrierApns apns = 3;</code>
     */
    public Builder setApns(
        com.nooriro.oneuplus.proto.googlecarrier.CarrierApns.Builder builderForValue) {
      copyOnWrite();
      instance.setApns(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .CarrierApns apns = 3;</code>
     */
    public Builder mergeApns(com.nooriro.oneuplus.proto.googlecarrier.CarrierApns value) {
      copyOnWrite();
      instance.mergeApns(value);
      return this;
    }
    /**
     * <code>optional .CarrierApns apns = 3;</code>
     */
    public Builder clearApns() {  copyOnWrite();
      instance.clearApns();
      return this;
    }

    /**
     * <code>optional .CarrierConfig configs = 4;</code>
     */
    @java.lang.Override
    public boolean hasConfigs() {
      return instance.hasConfigs();
    }
    /**
     * <code>optional .CarrierConfig configs = 4;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig getConfigs() {
      return instance.getConfigs();
    }
    /**
     * <code>optional .CarrierConfig configs = 4;</code>
     */
    public Builder setConfigs(com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig value) {
      copyOnWrite();
      instance.setConfigs(value);
      return this;
      }
    /**
     * <code>optional .CarrierConfig configs = 4;</code>
     */
    public Builder setConfigs(
        com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setConfigs(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .CarrierConfig configs = 4;</code>
     */
    public Builder mergeConfigs(com.nooriro.oneuplus.proto.googlecarrier.CarrierConfig value) {
      copyOnWrite();
      instance.mergeConfigs(value);
      return this;
    }
    /**
     * <code>optional .CarrierConfig configs = 4;</code>
     */
    public Builder clearConfigs() {  copyOnWrite();
      instance.clearConfigs();
      return this;
    }

    /**
     * <code>optional .VendorConfigs vendorConfigs = 5;</code>
     */
    @java.lang.Override
    public boolean hasVendorConfigs() {
      return instance.hasVendorConfigs();
    }
    /**
     * <code>optional .VendorConfigs vendorConfigs = 5;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs getVendorConfigs() {
      return instance.getVendorConfigs();
    }
    /**
     * <code>optional .VendorConfigs vendorConfigs = 5;</code>
     */
    public Builder setVendorConfigs(com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs value) {
      copyOnWrite();
      instance.setVendorConfigs(value);
      return this;
      }
    /**
     * <code>optional .VendorConfigs vendorConfigs = 5;</code>
     */
    public Builder setVendorConfigs(
        com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs.Builder builderForValue) {
      copyOnWrite();
      instance.setVendorConfigs(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .VendorConfigs vendorConfigs = 5;</code>
     */
    public Builder mergeVendorConfigs(com.nooriro.oneuplus.proto.googlecarrier.VendorConfigs value) {
      copyOnWrite();
      instance.mergeVendorConfigs(value);
      return this;
    }
    /**
     * <code>optional .VendorConfigs vendorConfigs = 5;</code>
     */
    public Builder clearVendorConfigs() {  copyOnWrite();
      instance.clearVendorConfigs();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CarrierSettings)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "canonicalName_",
            "version_",
            "apns_",
            "configs_",
            "vendorConfigs_",
          };
          java.lang.String info =
              "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0004\u0001\u1508\u0000\u0002" +
              "\u1002\u0001\u0003\u1409\u0002\u0004\u1409\u0003\u0005\u1409\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CarrierSettings)
  private static final com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings DEFAULT_INSTANCE;
  static {
    CarrierSettings defaultInstance = new CarrierSettings();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CarrierSettings.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CarrierSettings> PARSER;

  public static com.google.protobuf.Parser<CarrierSettings> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

