// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface CarrierIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarrierId)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required string mccMnc = 1;</code>
   * @return Whether the mccMnc field is set.
   */
  boolean hasMccMnc();
  /**
   * <code>required string mccMnc = 1;</code>
   * @return The mccMnc.
   */
  java.lang.String getMccMnc();
  /**
   * <code>required string mccMnc = 1;</code>
   * @return The bytes for mccMnc.
   */
  com.google.protobuf.ByteString
      getMccMncBytes();

  /**
   * <code>string spn = 2;</code>
   * @return Whether the spn field is set.
   */
  boolean hasSpn();
  /**
   * <code>string spn = 2;</code>
   * @return The spn.
   */
  java.lang.String getSpn();
  /**
   * <code>string spn = 2;</code>
   * @return The bytes for spn.
   */
  com.google.protobuf.ByteString
      getSpnBytes();

  /**
   * <code>string imsi = 3;</code>
   * @return Whether the imsi field is set.
   */
  boolean hasImsi();
  /**
   * <code>string imsi = 3;</code>
   * @return The imsi.
   */
  java.lang.String getImsi();
  /**
   * <code>string imsi = 3;</code>
   * @return The bytes for imsi.
   */
  com.google.protobuf.ByteString
      getImsiBytes();

  /**
   * <code>string gid1 = 4;</code>
   * @return Whether the gid1 field is set.
   */
  boolean hasGid1();
  /**
   * <code>string gid1 = 4;</code>
   * @return The gid1.
   */
  java.lang.String getGid1();
  /**
   * <code>string gid1 = 4;</code>
   * @return The bytes for gid1.
   */
  com.google.protobuf.ByteString
      getGid1Bytes();

  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @return Whether the gid2 field is set.
   */
  boolean hasGid2();
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @return The gid2.
   */
  java.lang.String getGid2();
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @return The bytes for gid2.
   */
  com.google.protobuf.ByteString
      getGid2Bytes();

  public com.nooriro.oneuplus.proto.googlecarrier.CarrierId.MvnoCase getMvnoCase();
}
