// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code CarrierList}
 */
public  final class CarrierList extends
    com.google.protobuf.GeneratedMessageLite<
        CarrierList, CarrierList.Builder> implements
    // @@protoc_insertion_point(message_implements:CarrierList)
    CarrierListOrBuilder {
  private CarrierList() {
    entry_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int ENTRY_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> entry_;
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> getEntryList() {
    return entry_;
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  public java.util.List<? extends com.nooriro.oneuplus.proto.googlecarrier.CarrierMapOrBuilder> 
      getEntryOrBuilderList() {
    return entry_;
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  @java.lang.Override
  public int getEntryCount() {
    return entry_.size();
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierMap getEntry(int index) {
    return entry_.get(index);
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierMapOrBuilder getEntryOrBuilder(
      int index) {
    return entry_.get(index);
  }
  private void ensureEntryIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> tmp = entry_;
    if (!tmp.isModifiable()) {
      entry_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  private void setEntry(
      int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierMap value) {
    value.getClass();
  ensureEntryIsMutable();
    entry_.set(index, value);
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  private void addEntry(com.nooriro.oneuplus.proto.googlecarrier.CarrierMap value) {
    value.getClass();
  ensureEntryIsMutable();
    entry_.add(value);
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  private void addEntry(
      int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierMap value) {
    value.getClass();
  ensureEntryIsMutable();
    entry_.add(index, value);
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  private void addAllEntry(
      java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> values) {
    ensureEntryIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, entry_);
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  private void clearEntry() {
    entry_ = emptyProtobufList();
  }
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  private void removeEntry(int index) {
    ensureEntryIsMutable();
    entry_.remove(index);
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private long version_;
  /**
   * <code>required int64 version = 2;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }
  /**
   * <code>required int64 version = 2;</code>
   * @param value The version to set.
   */
  private void setVersion(long value) {
    bitField0_ |= 0x00000001;
    version_ = value;
  }
  /**
   * <code>required int64 version = 2;</code>
   */
  private void clearVersion() {
    bitField0_ = (bitField0_ & ~0x00000001);
    version_ = 0L;
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.CarrierList prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CarrierList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.CarrierList, Builder> implements
      // @@protoc_insertion_point(builder_implements:CarrierList)
      com.nooriro.oneuplus.proto.googlecarrier.CarrierListOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.CarrierList.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> getEntryList() {
      return java.util.Collections.unmodifiableList(
          instance.getEntryList());
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    @java.lang.Override
    public int getEntryCount() {
      return instance.getEntryCount();
    }/**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.CarrierMap getEntry(int index) {
      return instance.getEntry(index);
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder setEntry(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierMap value) {
      copyOnWrite();
      instance.setEntry(index, value);
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder setEntry(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierMap.Builder builderForValue) {
      copyOnWrite();
      instance.setEntry(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder addEntry(com.nooriro.oneuplus.proto.googlecarrier.CarrierMap value) {
      copyOnWrite();
      instance.addEntry(value);
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder addEntry(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierMap value) {
      copyOnWrite();
      instance.addEntry(index, value);
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder addEntry(
        com.nooriro.oneuplus.proto.googlecarrier.CarrierMap.Builder builderForValue) {
      copyOnWrite();
      instance.addEntry(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder addEntry(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierMap.Builder builderForValue) {
      copyOnWrite();
      instance.addEntry(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder addAllEntry(
        java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> values) {
      copyOnWrite();
      instance.addAllEntry(values);
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder clearEntry() {
      copyOnWrite();
      instance.clearEntry();
      return this;
    }
    /**
     * <code>repeated .CarrierMap entry = 1;</code>
     */
    public Builder removeEntry(int index) {
      copyOnWrite();
      instance.removeEntry(index);
      return this;
    }

    /**
     * <code>required int64 version = 2;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <code>required int64 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>required int64 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>required int64 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CarrierList)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.CarrierList();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "entry_",
            com.nooriro.oneuplus.proto.googlecarrier.CarrierMap.class,
            "version_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0002\u0001\u041b\u0002\u1502" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.CarrierList> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.CarrierList.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.CarrierList>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CarrierList)
  private static final com.nooriro.oneuplus.proto.googlecarrier.CarrierList DEFAULT_INSTANCE;
  static {
    CarrierList defaultInstance = new CarrierList();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CarrierList.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CarrierList> PARSER;

  public static com.google.protobuf.Parser<CarrierList> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

