// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface CarrierMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarrierMap)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return Whether the canonicalName field is set.
   */
  boolean hasCanonicalName();
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return The canonicalName.
   */
  java.lang.String getCanonicalName();
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return The bytes for canonicalName.
   */
  com.google.protobuf.ByteString
      getCanonicalNameBytes();

  /**
   * <code>required .CarrierId carrierId = 2;</code>
   * @return Whether the carrierId field is set.
   */
  boolean hasCarrierId();
  /**
   * <code>required .CarrierId carrierId = 2;</code>
   * @return The carrierId.
   */
  com.nooriro.oneuplus.proto.googlecarrier.CarrierId getCarrierId();
}
