// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface CarrierListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarrierList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  java.util.List<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> 
      getEntryList();
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  com.nooriro.oneuplus.proto.googlecarrier.CarrierMap getEntry(int index);
  /**
   * <code>repeated .CarrierMap entry = 1;</code>
   */
  int getEntryCount();

  /**
   * <code>required int64 version = 2;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>required int64 version = 2;</code>
   * @return The version.
   */
  long getVersion();
}
