// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code CarrierApns}
 */
public  final class CarrierApns extends
    com.google.protobuf.GeneratedMessageLite<
        CarrierApns, CarrierApns.Builder> implements
    // @@protoc_insertion_point(message_implements:CarrierApns)
    CarrierApnsOrBuilder {
  private CarrierApns() {
    apn_ = emptyProtobufList();
  }
  public static final int APN_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.nooriro.oneuplus.proto.googlecarrier.ApnItem> apn_;
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.ApnItem> getApnList() {
    return apn_;
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  public java.util.List<? extends com.nooriro.oneuplus.proto.googlecarrier.ApnItemOrBuilder> 
      getApnOrBuilderList() {
    return apn_;
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  @java.lang.Override
  public int getApnCount() {
    return apn_.size();
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.ApnItem getApn(int index) {
    return apn_.get(index);
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  public com.nooriro.oneuplus.proto.googlecarrier.ApnItemOrBuilder getApnOrBuilder(
      int index) {
    return apn_.get(index);
  }
  private void ensureApnIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.nooriro.oneuplus.proto.googlecarrier.ApnItem> tmp = apn_;
    if (!tmp.isModifiable()) {
      apn_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  private void setApn(
      int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem value) {
    value.getClass();
  ensureApnIsMutable();
    apn_.set(index, value);
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  private void addApn(com.nooriro.oneuplus.proto.googlecarrier.ApnItem value) {
    value.getClass();
  ensureApnIsMutable();
    apn_.add(value);
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  private void addApn(
      int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem value) {
    value.getClass();
  ensureApnIsMutable();
    apn_.add(index, value);
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  private void addAllApn(
      java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.ApnItem> values) {
    ensureApnIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, apn_);
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  private void clearApn() {
    apn_ = emptyProtobufList();
  }
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  private void removeApn(int index) {
    ensureApnIsMutable();
    apn_.remove(index);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.CarrierApns prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CarrierApns}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.CarrierApns, Builder> implements
      // @@protoc_insertion_point(builder_implements:CarrierApns)
      com.nooriro.oneuplus.proto.googlecarrier.CarrierApnsOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.CarrierApns.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.ApnItem> getApnList() {
      return java.util.Collections.unmodifiableList(
          instance.getApnList());
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    @java.lang.Override
    public int getApnCount() {
      return instance.getApnCount();
    }/**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.ApnItem getApn(int index) {
      return instance.getApn(index);
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder setApn(
        int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem value) {
      copyOnWrite();
      instance.setApn(index, value);
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder setApn(
        int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Builder builderForValue) {
      copyOnWrite();
      instance.setApn(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder addApn(com.nooriro.oneuplus.proto.googlecarrier.ApnItem value) {
      copyOnWrite();
      instance.addApn(value);
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder addApn(
        int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem value) {
      copyOnWrite();
      instance.addApn(index, value);
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder addApn(
        com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Builder builderForValue) {
      copyOnWrite();
      instance.addApn(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder addApn(
        int index, com.nooriro.oneuplus.proto.googlecarrier.ApnItem.Builder builderForValue) {
      copyOnWrite();
      instance.addApn(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder addAllApn(
        java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.ApnItem> values) {
      copyOnWrite();
      instance.addAllApn(values);
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder clearApn() {
      copyOnWrite();
      instance.clearApn();
      return this;
    }
    /**
     * <code>repeated .ApnItem apn = 2;</code>
     */
    public Builder removeApn(int index) {
      copyOnWrite();
      instance.removeApn(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CarrierApns)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.CarrierApns();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "apn_",
            com.nooriro.oneuplus.proto.googlecarrier.ApnItem.class,
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0000\u0002\u0002\u0001\u0000\u0001\u0001\u0002\u041b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.CarrierApns> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.CarrierApns.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.CarrierApns>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CarrierApns)
  private static final com.nooriro.oneuplus.proto.googlecarrier.CarrierApns DEFAULT_INSTANCE;
  static {
    CarrierApns defaultInstance = new CarrierApns();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CarrierApns.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierApns getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CarrierApns> PARSER;

  public static com.google.protobuf.Parser<CarrierApns> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

