// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface CarrierConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarrierConfig)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .Config config = 2;</code>
   */
  java.util.List<com.nooriro.oneuplus.proto.googlecarrier.Config> 
      getConfigList();
  /**
   * <code>repeated .Config config = 2;</code>
   */
  com.nooriro.oneuplus.proto.googlecarrier.Config getConfig(int index);
  /**
   * <code>repeated .Config config = 2;</code>
   */
  int getConfigCount();
}
