// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code CarrierId}
 */
public  final class CarrierId extends
    com.google.protobuf.GeneratedMessageLite<
        CarrierId, CarrierId.Builder> implements
    // @@protoc_insertion_point(message_implements:CarrierId)
    CarrierIdOrBuilder {
  private CarrierId() {
    mccMnc_ = "";
  }
  private int bitField0_;
  private int mvnoCase_ = 0;
  private java.lang.Object mvno_;
  public enum MvnoCase {
    SPN(2),
    IMSI(3),
    GID1(4),
    GID2(5),
    MVNO_NOT_SET(0);
    private final int value;
    private MvnoCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MvnoCase valueOf(int value) {
      return forNumber(value);
    }

    public static MvnoCase forNumber(int value) {
      switch (value) {
        case 2: return SPN;
        case 3: return IMSI;
        case 4: return GID1;
        case 5: return GID2;
        case 0: return MVNO_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MvnoCase
  getMvnoCase() {
    return MvnoCase.forNumber(
        mvnoCase_);
  }

  private void clearMvno() {
    mvnoCase_ = 0;
    mvno_ = null;
  }

  public static final int MCCMNC_FIELD_NUMBER = 1;
  private java.lang.String mccMnc_;
  /**
   * <code>required string mccMnc = 1;</code>
   * @return Whether the mccMnc field is set.
   */
  @java.lang.Override
  public boolean hasMccMnc() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string mccMnc = 1;</code>
   * @return The mccMnc.
   */
  @java.lang.Override
  public java.lang.String getMccMnc() {
    return mccMnc_;
  }
  /**
   * <code>required string mccMnc = 1;</code>
   * @return The bytes for mccMnc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMccMncBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mccMnc_);
  }
  /**
   * <code>required string mccMnc = 1;</code>
   * @param value The mccMnc to set.
   */
  private void setMccMnc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    mccMnc_ = value;
  }
  /**
   * <code>required string mccMnc = 1;</code>
   */
  private void clearMccMnc() {
    bitField0_ = (bitField0_ & ~0x00000001);
    mccMnc_ = getDefaultInstance().getMccMnc();
  }
  /**
   * <code>required string mccMnc = 1;</code>
   * @param value The bytes for mccMnc to set.
   */
  private void setMccMncBytes(
      com.google.protobuf.ByteString value) {
    mccMnc_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int SPN_FIELD_NUMBER = 2;
  /**
   * <code>string spn = 2;</code>
   * @return Whether the spn field is set.
   */
  @java.lang.Override
  public boolean hasSpn() {
    return mvnoCase_ == 2;
  }
  /**
   * <code>string spn = 2;</code>
   * @return The spn.
   */
  @java.lang.Override
  public java.lang.String getSpn() {
    java.lang.String ref = "";
    if (mvnoCase_ == 2) {
      ref = (java.lang.String) mvno_;
    }
    return ref;
  }
  /**
   * <code>string spn = 2;</code>
   * @return The bytes for spn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpnBytes() {
    java.lang.String ref = "";
    if (mvnoCase_ == 2) {
      ref = (java.lang.String) mvno_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string spn = 2;</code>
   * @param value The spn to set.
   */
  private void setSpn(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  mvnoCase_ = 2;
    mvno_ = value;
  }
  /**
   * <code>string spn = 2;</code>
   */
  private void clearSpn() {
    if (mvnoCase_ == 2) {
      mvnoCase_ = 0;
      mvno_ = null;
    }
  }
  /**
   * <code>string spn = 2;</code>
   * @param value The bytes for spn to set.
   */
  private void setSpnBytes(
      com.google.protobuf.ByteString value) {
    mvno_ = value.toStringUtf8();
    mvnoCase_ = 2;
  }

  public static final int IMSI_FIELD_NUMBER = 3;
  /**
   * <code>string imsi = 3;</code>
   * @return Whether the imsi field is set.
   */
  @java.lang.Override
  public boolean hasImsi() {
    return mvnoCase_ == 3;
  }
  /**
   * <code>string imsi = 3;</code>
   * @return The imsi.
   */
  @java.lang.Override
  public java.lang.String getImsi() {
    java.lang.String ref = "";
    if (mvnoCase_ == 3) {
      ref = (java.lang.String) mvno_;
    }
    return ref;
  }
  /**
   * <code>string imsi = 3;</code>
   * @return The bytes for imsi.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImsiBytes() {
    java.lang.String ref = "";
    if (mvnoCase_ == 3) {
      ref = (java.lang.String) mvno_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string imsi = 3;</code>
   * @param value The imsi to set.
   */
  private void setImsi(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  mvnoCase_ = 3;
    mvno_ = value;
  }
  /**
   * <code>string imsi = 3;</code>
   */
  private void clearImsi() {
    if (mvnoCase_ == 3) {
      mvnoCase_ = 0;
      mvno_ = null;
    }
  }
  /**
   * <code>string imsi = 3;</code>
   * @param value The bytes for imsi to set.
   */
  private void setImsiBytes(
      com.google.protobuf.ByteString value) {
    mvno_ = value.toStringUtf8();
    mvnoCase_ = 3;
  }

  public static final int GID1_FIELD_NUMBER = 4;
  /**
   * <code>string gid1 = 4;</code>
   * @return Whether the gid1 field is set.
   */
  @java.lang.Override
  public boolean hasGid1() {
    return mvnoCase_ == 4;
  }
  /**
   * <code>string gid1 = 4;</code>
   * @return The gid1.
   */
  @java.lang.Override
  public java.lang.String getGid1() {
    java.lang.String ref = "";
    if (mvnoCase_ == 4) {
      ref = (java.lang.String) mvno_;
    }
    return ref;
  }
  /**
   * <code>string gid1 = 4;</code>
   * @return The bytes for gid1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGid1Bytes() {
    java.lang.String ref = "";
    if (mvnoCase_ == 4) {
      ref = (java.lang.String) mvno_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string gid1 = 4;</code>
   * @param value The gid1 to set.
   */
  private void setGid1(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  mvnoCase_ = 4;
    mvno_ = value;
  }
  /**
   * <code>string gid1 = 4;</code>
   */
  private void clearGid1() {
    if (mvnoCase_ == 4) {
      mvnoCase_ = 0;
      mvno_ = null;
    }
  }
  /**
   * <code>string gid1 = 4;</code>
   * @param value The bytes for gid1 to set.
   */
  private void setGid1Bytes(
      com.google.protobuf.ByteString value) {
    mvno_ = value.toStringUtf8();
    mvnoCase_ = 4;
  }

  public static final int GID2_FIELD_NUMBER = 5;
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @return Whether the gid2 field is set.
   */
  @java.lang.Override
  public boolean hasGid2() {
    return mvnoCase_ == 5;
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @return The gid2.
   */
  @java.lang.Override
  public java.lang.String getGid2() {
    java.lang.String ref = "";
    if (mvnoCase_ == 5) {
      ref = (java.lang.String) mvno_;
    }
    return ref;
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @return The bytes for gid2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGid2Bytes() {
    java.lang.String ref = "";
    if (mvnoCase_ == 5) {
      ref = (java.lang.String) mvno_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @param value The gid2 to set.
   */
  private void setGid2(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  mvnoCase_ = 5;
    mvno_ = value;
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   */
  private void clearGid2() {
    if (mvnoCase_ == 5) {
      mvnoCase_ = 0;
      mvno_ = null;
    }
  }
  /**
   * <pre>
   * deprecated
   * </pre>
   *
   * <code>string gid2 = 5;</code>
   * @param value The bytes for gid2 to set.
   */
  private void setGid2Bytes(
      com.google.protobuf.ByteString value) {
    mvno_ = value.toStringUtf8();
    mvnoCase_ = 5;
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.CarrierId prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CarrierId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.CarrierId, Builder> implements
      // @@protoc_insertion_point(builder_implements:CarrierId)
      com.nooriro.oneuplus.proto.googlecarrier.CarrierIdOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.CarrierId.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MvnoCase
        getMvnoCase() {
      return instance.getMvnoCase();
    }

    public Builder clearMvno() {
      copyOnWrite();
      instance.clearMvno();
      return this;
    }


    /**
     * <code>required string mccMnc = 1;</code>
     * @return Whether the mccMnc field is set.
     */
    @java.lang.Override
    public boolean hasMccMnc() {
      return instance.hasMccMnc();
    }
    /**
     * <code>required string mccMnc = 1;</code>
     * @return The mccMnc.
     */
    @java.lang.Override
    public java.lang.String getMccMnc() {
      return instance.getMccMnc();
    }
    /**
     * <code>required string mccMnc = 1;</code>
     * @return The bytes for mccMnc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMccMncBytes() {
      return instance.getMccMncBytes();
    }
    /**
     * <code>required string mccMnc = 1;</code>
     * @param value The mccMnc to set.
     * @return This builder for chaining.
     */
    public Builder setMccMnc(
        java.lang.String value) {
      copyOnWrite();
      instance.setMccMnc(value);
      return this;
    }
    /**
     * <code>required string mccMnc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMccMnc() {
      copyOnWrite();
      instance.clearMccMnc();
      return this;
    }
    /**
     * <code>required string mccMnc = 1;</code>
     * @param value The bytes for mccMnc to set.
     * @return This builder for chaining.
     */
    public Builder setMccMncBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMccMncBytes(value);
      return this;
    }

    /**
     * <code>string spn = 2;</code>
     * @return Whether the spn field is set.
     */
    @java.lang.Override
    public boolean hasSpn() {
      return instance.hasSpn();
    }
    /**
     * <code>string spn = 2;</code>
     * @return The spn.
     */
    @java.lang.Override
    public java.lang.String getSpn() {
      return instance.getSpn();
    }
    /**
     * <code>string spn = 2;</code>
     * @return The bytes for spn.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSpnBytes() {
      return instance.getSpnBytes();
    }
    /**
     * <code>string spn = 2;</code>
     * @param value The spn to set.
     * @return This builder for chaining.
     */
    public Builder setSpn(
        java.lang.String value) {
      copyOnWrite();
      instance.setSpn(value);
      return this;
    }
    /**
     * <code>string spn = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpn() {
      copyOnWrite();
      instance.clearSpn();
      return this;
    }
    /**
     * <code>string spn = 2;</code>
     * @param value The bytes for spn to set.
     * @return This builder for chaining.
     */
    public Builder setSpnBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSpnBytes(value);
      return this;
    }

    /**
     * <code>string imsi = 3;</code>
     * @return Whether the imsi field is set.
     */
    @java.lang.Override
    public boolean hasImsi() {
      return instance.hasImsi();
    }
    /**
     * <code>string imsi = 3;</code>
     * @return The imsi.
     */
    @java.lang.Override
    public java.lang.String getImsi() {
      return instance.getImsi();
    }
    /**
     * <code>string imsi = 3;</code>
     * @return The bytes for imsi.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImsiBytes() {
      return instance.getImsiBytes();
    }
    /**
     * <code>string imsi = 3;</code>
     * @param value The imsi to set.
     * @return This builder for chaining.
     */
    public Builder setImsi(
        java.lang.String value) {
      copyOnWrite();
      instance.setImsi(value);
      return this;
    }
    /**
     * <code>string imsi = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImsi() {
      copyOnWrite();
      instance.clearImsi();
      return this;
    }
    /**
     * <code>string imsi = 3;</code>
     * @param value The bytes for imsi to set.
     * @return This builder for chaining.
     */
    public Builder setImsiBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImsiBytes(value);
      return this;
    }

    /**
     * <code>string gid1 = 4;</code>
     * @return Whether the gid1 field is set.
     */
    @java.lang.Override
    public boolean hasGid1() {
      return instance.hasGid1();
    }
    /**
     * <code>string gid1 = 4;</code>
     * @return The gid1.
     */
    @java.lang.Override
    public java.lang.String getGid1() {
      return instance.getGid1();
    }
    /**
     * <code>string gid1 = 4;</code>
     * @return The bytes for gid1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGid1Bytes() {
      return instance.getGid1Bytes();
    }
    /**
     * <code>string gid1 = 4;</code>
     * @param value The gid1 to set.
     * @return This builder for chaining.
     */
    public Builder setGid1(
        java.lang.String value) {
      copyOnWrite();
      instance.setGid1(value);
      return this;
    }
    /**
     * <code>string gid1 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGid1() {
      copyOnWrite();
      instance.clearGid1();
      return this;
    }
    /**
     * <code>string gid1 = 4;</code>
     * @param value The bytes for gid1 to set.
     * @return This builder for chaining.
     */
    public Builder setGid1Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGid1Bytes(value);
      return this;
    }

    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>string gid2 = 5;</code>
     * @return Whether the gid2 field is set.
     */
    @java.lang.Override
    public boolean hasGid2() {
      return instance.hasGid2();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>string gid2 = 5;</code>
     * @return The gid2.
     */
    @java.lang.Override
    public java.lang.String getGid2() {
      return instance.getGid2();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>string gid2 = 5;</code>
     * @return The bytes for gid2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGid2Bytes() {
      return instance.getGid2Bytes();
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>string gid2 = 5;</code>
     * @param value The gid2 to set.
     * @return This builder for chaining.
     */
    public Builder setGid2(
        java.lang.String value) {
      copyOnWrite();
      instance.setGid2(value);
      return this;
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>string gid2 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGid2() {
      copyOnWrite();
      instance.clearGid2();
      return this;
    }
    /**
     * <pre>
     * deprecated
     * </pre>
     *
     * <code>string gid2 = 5;</code>
     * @param value The bytes for gid2 to set.
     * @return This builder for chaining.
     */
    public Builder setGid2Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGid2Bytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CarrierId)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.CarrierId();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "mvno_",
            "mvnoCase_",
            "bitField0_",
            "mccMnc_",
          };
          java.lang.String info =
              "\u0001\u0005\u0001\u0001\u0001\u0005\u0005\u0000\u0000\u0001\u0001\u1508\u0000\u0002" +
              "\u103b\u0000\u0003\u103b\u0000\u0004\u103b\u0000\u0005\u103b\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.CarrierId> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.CarrierId.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.CarrierId>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CarrierId)
  private static final com.nooriro.oneuplus.proto.googlecarrier.CarrierId DEFAULT_INSTANCE;
  static {
    CarrierId defaultInstance = new CarrierId();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CarrierId.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CarrierId> PARSER;

  public static com.google.protobuf.Parser<CarrierId> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

