// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code CarrierMap}
 */
public  final class CarrierMap extends
    com.google.protobuf.GeneratedMessageLite<
        CarrierMap, CarrierMap.Builder> implements
    // @@protoc_insertion_point(message_implements:CarrierMap)
    CarrierMapOrBuilder {
  private CarrierMap() {
    canonicalName_ = "";
  }
  private int bitField0_;
  public static final int CANONICALNAME_FIELD_NUMBER = 1;
  private java.lang.String canonicalName_;
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return Whether the canonicalName field is set.
   */
  @java.lang.Override
  public boolean hasCanonicalName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return The canonicalName.
   */
  @java.lang.Override
  public java.lang.String getCanonicalName() {
    return canonicalName_;
  }
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @return The bytes for canonicalName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCanonicalNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(canonicalName_);
  }
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @param value The canonicalName to set.
   */
  private void setCanonicalName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    canonicalName_ = value;
  }
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   */
  private void clearCanonicalName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    canonicalName_ = getDefaultInstance().getCanonicalName();
  }
  /**
   * <pre>
   * canonicalName is not unique in CarrierList, e.g., the same settings
   * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
   * key in CarrierSettings.
   * </pre>
   *
   * <code>required string canonicalName = 1;</code>
   * @param value The bytes for canonicalName to set.
   */
  private void setCanonicalNameBytes(
      com.google.protobuf.ByteString value) {
    canonicalName_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int CARRIERID_FIELD_NUMBER = 2;
  private com.nooriro.oneuplus.proto.googlecarrier.CarrierId carrierId_;
  /**
   * <code>required .CarrierId carrierId = 2;</code>
   */
  @java.lang.Override
  public boolean hasCarrierId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required .CarrierId carrierId = 2;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierId getCarrierId() {
    return carrierId_ == null ? com.nooriro.oneuplus.proto.googlecarrier.CarrierId.getDefaultInstance() : carrierId_;
  }
  /**
   * <code>required .CarrierId carrierId = 2;</code>
   */
  private void setCarrierId(com.nooriro.oneuplus.proto.googlecarrier.CarrierId value) {
    value.getClass();
  carrierId_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>required .CarrierId carrierId = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCarrierId(com.nooriro.oneuplus.proto.googlecarrier.CarrierId value) {
    value.getClass();
  if (carrierId_ != null &&
        carrierId_ != com.nooriro.oneuplus.proto.googlecarrier.CarrierId.getDefaultInstance()) {
      carrierId_ =
        com.nooriro.oneuplus.proto.googlecarrier.CarrierId.newBuilder(carrierId_).mergeFrom(value).buildPartial();
    } else {
      carrierId_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>required .CarrierId carrierId = 2;</code>
   */
  private void clearCarrierId() {  carrierId_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.CarrierMap prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code CarrierMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.CarrierMap, Builder> implements
      // @@protoc_insertion_point(builder_implements:CarrierMap)
      com.nooriro.oneuplus.proto.googlecarrier.CarrierMapOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.CarrierMap.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * canonicalName is not unique in CarrierList, e.g., the same settings
     * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
     * key in CarrierSettings.
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return Whether the canonicalName field is set.
     */
    @java.lang.Override
    public boolean hasCanonicalName() {
      return instance.hasCanonicalName();
    }
    /**
     * <pre>
     * canonicalName is not unique in CarrierList, e.g., the same settings
     * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
     * key in CarrierSettings.
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return The canonicalName.
     */
    @java.lang.Override
    public java.lang.String getCanonicalName() {
      return instance.getCanonicalName();
    }
    /**
     * <pre>
     * canonicalName is not unique in CarrierList, e.g., the same settings
     * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
     * key in CarrierSettings.
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return The bytes for canonicalName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCanonicalNameBytes() {
      return instance.getCanonicalNameBytes();
    }
    /**
     * <pre>
     * canonicalName is not unique in CarrierList, e.g., the same settings
     * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
     * key in CarrierSettings.
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @param value The canonicalName to set.
     * @return This builder for chaining.
     */
    public Builder setCanonicalName(
        java.lang.String value) {
      copyOnWrite();
      instance.setCanonicalName(value);
      return this;
    }
    /**
     * <pre>
     * canonicalName is not unique in CarrierList, e.g., the same settings
     * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
     * key in CarrierSettings.
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanonicalName() {
      copyOnWrite();
      instance.clearCanonicalName();
      return this;
    }
    /**
     * <pre>
     * canonicalName is not unique in CarrierList, e.g., the same settings
     * may apply to multiple MCCMNCs or MVNOs. Use this field as the lookup
     * key in CarrierSettings.
     * </pre>
     *
     * <code>required string canonicalName = 1;</code>
     * @param value The bytes for canonicalName to set.
     * @return This builder for chaining.
     */
    public Builder setCanonicalNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCanonicalNameBytes(value);
      return this;
    }

    /**
     * <code>required .CarrierId carrierId = 2;</code>
     */
    @java.lang.Override
    public boolean hasCarrierId() {
      return instance.hasCarrierId();
    }
    /**
     * <code>required .CarrierId carrierId = 2;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.CarrierId getCarrierId() {
      return instance.getCarrierId();
    }
    /**
     * <code>required .CarrierId carrierId = 2;</code>
     */
    public Builder setCarrierId(com.nooriro.oneuplus.proto.googlecarrier.CarrierId value) {
      copyOnWrite();
      instance.setCarrierId(value);
      return this;
      }
    /**
     * <code>required .CarrierId carrierId = 2;</code>
     */
    public Builder setCarrierId(
        com.nooriro.oneuplus.proto.googlecarrier.CarrierId.Builder builderForValue) {
      copyOnWrite();
      instance.setCarrierId(builderForValue.build());
      return this;
    }
    /**
     * <code>required .CarrierId carrierId = 2;</code>
     */
    public Builder mergeCarrierId(com.nooriro.oneuplus.proto.googlecarrier.CarrierId value) {
      copyOnWrite();
      instance.mergeCarrierId(value);
      return this;
    }
    /**
     * <code>required .CarrierId carrierId = 2;</code>
     */
    public Builder clearCarrierId() {  copyOnWrite();
      instance.clearCarrierId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CarrierMap)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.CarrierMap();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "canonicalName_",
            "carrierId_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u1508\u0000\u0002" +
              "\u1509\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.CarrierMap.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.CarrierMap>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CarrierMap)
  private static final com.nooriro.oneuplus.proto.googlecarrier.CarrierMap DEFAULT_INSTANCE;
  static {
    CarrierMap defaultInstance = new CarrierMap();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CarrierMap.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.CarrierMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CarrierMap> PARSER;

  public static com.google.protobuf.Parser<CarrierMap> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

