// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface CarrierApnsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CarrierApns)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  java.util.List<com.nooriro.oneuplus.proto.googlecarrier.ApnItem> 
      getApnList();
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  com.nooriro.oneuplus.proto.googlecarrier.ApnItem getApn(int index);
  /**
   * <code>repeated .ApnItem apn = 2;</code>
   */
  int getApnCount();
}
