// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code IntArray}
 */
public  final class IntArray extends
    com.google.protobuf.GeneratedMessageLite<
        IntArray, IntArray.Builder> implements
    // @@protoc_insertion_point(message_implements:IntArray)
    IntArrayOrBuilder {
  private IntArray() {
    item_ = emptyIntList();
  }
  public static final int ITEM_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList item_;
  /**
   * <code>repeated int32 item = 1;</code>
   * @return A list containing the item.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getItemList() {
    return item_;
  }
  /**
   * <code>repeated int32 item = 1;</code>
   * @return The count of item.
   */
  @java.lang.Override
  public int getItemCount() {
    return item_.size();
  }
  /**
   * <code>repeated int32 item = 1;</code>
   * @param index The index of the element to return.
   * @return The item at the given index.
   */
  @java.lang.Override
  public int getItem(int index) {
    return item_.getInt(index);
  }
  private void ensureItemIsMutable() {
    com.google.protobuf.Internal.IntList tmp = item_;
    if (!tmp.isModifiable()) {
      item_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int32 item = 1;</code>
   * @param index The index to set the value at.
   * @param value The item to set.
   */
  private void setItem(
      int index, int value) {
    ensureItemIsMutable();
    item_.setInt(index, value);
  }
  /**
   * <code>repeated int32 item = 1;</code>
   * @param value The item to add.
   */
  private void addItem(int value) {
    ensureItemIsMutable();
    item_.addInt(value);
  }
  /**
   * <code>repeated int32 item = 1;</code>
   * @param values The item to add.
   */
  private void addAllItem(
      java.lang.Iterable<? extends java.lang.Integer> values) {
    ensureItemIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, item_);
  }
  /**
   * <code>repeated int32 item = 1;</code>
   */
  private void clearItem() {
    item_ = emptyIntList();
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.IntArray prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code IntArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.IntArray, Builder> implements
      // @@protoc_insertion_point(builder_implements:IntArray)
      com.nooriro.oneuplus.proto.googlecarrier.IntArrayOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.IntArray.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated int32 item = 1;</code>
     * @return A list containing the item.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getItemList() {
      return java.util.Collections.unmodifiableList(
          instance.getItemList());
    }
    /**
     * <code>repeated int32 item = 1;</code>
     * @return The count of item.
     */
    @java.lang.Override
    public int getItemCount() {
      return instance.getItemCount();
    }
    /**
     * <code>repeated int32 item = 1;</code>
     * @param index The index of the element to return.
     * @return The item at the given index.
     */
    @java.lang.Override
    public int getItem(int index) {
      return instance.getItem(index);
    }
    /**
     * <code>repeated int32 item = 1;</code>
     * @param value The item to set.
     * @return This builder for chaining.
     */
    public Builder setItem(
        int index, int value) {
      copyOnWrite();
      instance.setItem(index, value);
      return this;
    }
    /**
     * <code>repeated int32 item = 1;</code>
     * @param value The item to add.
     * @return This builder for chaining.
     */
    public Builder addItem(int value) {
      copyOnWrite();
      instance.addItem(value);
      return this;
    }
    /**
     * <code>repeated int32 item = 1;</code>
     * @param values The item to add.
     * @return This builder for chaining.
     */
    public Builder addAllItem(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllItem(values);
      return this;
    }
    /**
     * <code>repeated int32 item = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItem() {
      copyOnWrite();
      instance.clearItem();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:IntArray)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.IntArray();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "item_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u0016";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.IntArray> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.IntArray.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.IntArray>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:IntArray)
  private static final com.nooriro.oneuplus.proto.googlecarrier.IntArray DEFAULT_INSTANCE;
  static {
    IntArray defaultInstance = new IntArray();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      IntArray.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.IntArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<IntArray> PARSER;

  public static com.google.protobuf.Parser<IntArray> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

