// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface IntArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntArray)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated int32 item = 1;</code>
   * @return A list containing the item.
   */
  java.util.List<java.lang.Integer> getItemList();
  /**
   * <code>repeated int32 item = 1;</code>
   * @return The count of item.
   */
  int getItemCount();
  /**
   * <code>repeated int32 item = 1;</code>
   * @param index The index of the element to return.
   * @return The item at the given index.
   */
  int getItem(int index);
}
