// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface MultiCarrierSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MultiCarrierSettings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>required int64 version = 1;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  java.util.List<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> 
      getSettingList();
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings getSetting(int index);
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  int getSettingCount();
}
