// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code MultiCarrierSettings}
 */
public  final class MultiCarrierSettings extends
    com.google.protobuf.GeneratedMessageLite<
        MultiCarrierSettings, MultiCarrierSettings.Builder> implements
    // @@protoc_insertion_point(message_implements:MultiCarrierSettings)
    MultiCarrierSettingsOrBuilder {
  private MultiCarrierSettings() {
    setting_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private long version_;
  /**
   * <code>required int64 version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }
  /**
   * <code>required int64 version = 1;</code>
   * @param value The version to set.
   */
  private void setVersion(long value) {
    bitField0_ |= 0x00000001;
    version_ = value;
  }
  /**
   * <code>required int64 version = 1;</code>
   */
  private void clearVersion() {
    bitField0_ = (bitField0_ & ~0x00000001);
    version_ = 0L;
  }

  public static final int SETTING_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> setting_;
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> getSettingList() {
    return setting_;
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  public java.util.List<? extends com.nooriro.oneuplus.proto.googlecarrier.CarrierSettingsOrBuilder> 
      getSettingOrBuilderList() {
    return setting_;
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  @java.lang.Override
  public int getSettingCount() {
    return setting_.size();
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  @java.lang.Override
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings getSetting(int index) {
    return setting_.get(index);
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  public com.nooriro.oneuplus.proto.googlecarrier.CarrierSettingsOrBuilder getSettingOrBuilder(
      int index) {
    return setting_.get(index);
  }
  private void ensureSettingIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> tmp = setting_;
    if (!tmp.isModifiable()) {
      setting_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  private void setSetting(
      int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings value) {
    value.getClass();
  ensureSettingIsMutable();
    setting_.set(index, value);
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  private void addSetting(com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings value) {
    value.getClass();
  ensureSettingIsMutable();
    setting_.add(value);
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  private void addSetting(
      int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings value) {
    value.getClass();
  ensureSettingIsMutable();
    setting_.add(index, value);
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  private void addAllSetting(
      java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> values) {
    ensureSettingIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, setting_);
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  private void clearSetting() {
    setting_ = emptyProtobufList();
  }
  /**
   * <code>repeated .CarrierSettings setting = 2;</code>
   */
  private void removeSetting(int index) {
    ensureSettingIsMutable();
    setting_.remove(index);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code MultiCarrierSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings, Builder> implements
      // @@protoc_insertion_point(builder_implements:MultiCarrierSettings)
      com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettingsOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required int64 version = 1;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return instance.hasVersion();
    }
    /**
     * <code>required int64 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>required int64 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>required int64 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> getSettingList() {
      return java.util.Collections.unmodifiableList(
          instance.getSettingList());
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    @java.lang.Override
    public int getSettingCount() {
      return instance.getSettingCount();
    }/**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    @java.lang.Override
    public com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings getSetting(int index) {
      return instance.getSetting(index);
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder setSetting(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings value) {
      copyOnWrite();
      instance.setSetting(index, value);
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder setSetting(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings.Builder builderForValue) {
      copyOnWrite();
      instance.setSetting(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder addSetting(com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings value) {
      copyOnWrite();
      instance.addSetting(value);
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder addSetting(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings value) {
      copyOnWrite();
      instance.addSetting(index, value);
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder addSetting(
        com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings.Builder builderForValue) {
      copyOnWrite();
      instance.addSetting(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder addSetting(
        int index, com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings.Builder builderForValue) {
      copyOnWrite();
      instance.addSetting(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder addAllSetting(
        java.lang.Iterable<? extends com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings> values) {
      copyOnWrite();
      instance.addAllSetting(values);
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder clearSetting() {
      copyOnWrite();
      instance.clearSetting();
      return this;
    }
    /**
     * <code>repeated .CarrierSettings setting = 2;</code>
     */
    public Builder removeSetting(int index) {
      copyOnWrite();
      instance.removeSetting(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:MultiCarrierSettings)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "version_",
            "setting_",
            com.nooriro.oneuplus.proto.googlecarrier.CarrierSettings.class,
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0002\u0001\u1502\u0000\u0002" +
              "\u041b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return memoizedIsInitialized;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:MultiCarrierSettings)
  private static final com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings DEFAULT_INSTANCE;
  static {
    MultiCarrierSettings defaultInstance = new MultiCarrierSettings();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MultiCarrierSettings.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.MultiCarrierSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MultiCarrierSettings> PARSER;

  public static com.google.protobuf.Parser<MultiCarrierSettings> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

