// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface TextArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TextArray)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated string item = 1;</code>
   * @return A list containing the item.
   */
  java.util.List<java.lang.String>
      getItemList();
  /**
   * <code>repeated string item = 1;</code>
   * @return The count of item.
   */
  int getItemCount();
  /**
   * <code>repeated string item = 1;</code>
   * @param index The index of the element to return.
   * @return The item at the given index.
   */
  java.lang.String getItem(int index);
  /**
   * <code>repeated string item = 1;</code>
   * @param index The index of the element to return.
   * @return The item at the given index.
   */
  com.google.protobuf.ByteString
      getItemBytes(int index);
}
