// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

/**
 * Protobuf type {@code TextArray}
 */
public  final class TextArray extends
    com.google.protobuf.GeneratedMessageLite<
        TextArray, TextArray.Builder> implements
    // @@protoc_insertion_point(message_implements:TextArray)
    TextArrayOrBuilder {
  private TextArray() {
    item_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int ITEM_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> item_;
  /**
   * <code>repeated string item = 1;</code>
   * @return A list containing the item.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getItemList() {
    return item_;
  }
  /**
   * <code>repeated string item = 1;</code>
   * @return The count of item.
   */
  @java.lang.Override
  public int getItemCount() {
    return item_.size();
  }
  /**
   * <code>repeated string item = 1;</code>
   * @param index The index of the element to return.
   * @return The item at the given index.
   */
  @java.lang.Override
  public java.lang.String getItem(int index) {
    return item_.get(index);
  }
  /**
   * <code>repeated string item = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the item at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        item_.get(index));
  }
  private void ensureItemIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        item_;  if (!tmp.isModifiable()) {
      item_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string item = 1;</code>
   * @param index The index to set the value at.
   * @param value The item to set.
   */
  private void setItem(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureItemIsMutable();
    item_.set(index, value);
  }
  /**
   * <code>repeated string item = 1;</code>
   * @param value The item to add.
   */
  private void addItem(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureItemIsMutable();
    item_.add(value);
  }
  /**
   * <code>repeated string item = 1;</code>
   * @param values The item to add.
   */
  private void addAllItem(
      java.lang.Iterable<java.lang.String> values) {
    ensureItemIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, item_);
  }
  /**
   * <code>repeated string item = 1;</code>
   */
  private void clearItem() {
    item_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string item = 1;</code>
   * @param value The bytes of the item to add.
   */
  private void addItemBytes(
      com.google.protobuf.ByteString value) {
    ensureItemIsMutable();
    item_.add(value.toStringUtf8());
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.nooriro.oneuplus.proto.googlecarrier.TextArray prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code TextArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.nooriro.oneuplus.proto.googlecarrier.TextArray, Builder> implements
      // @@protoc_insertion_point(builder_implements:TextArray)
      com.nooriro.oneuplus.proto.googlecarrier.TextArrayOrBuilder {
    // Construct using com.nooriro.oneuplus.proto.googlecarrier.TextArray.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string item = 1;</code>
     * @return A list containing the item.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getItemList() {
      return java.util.Collections.unmodifiableList(
          instance.getItemList());
    }
    /**
     * <code>repeated string item = 1;</code>
     * @return The count of item.
     */
    @java.lang.Override
    public int getItemCount() {
      return instance.getItemCount();
    }
    /**
     * <code>repeated string item = 1;</code>
     * @param index The index of the element to return.
     * @return The item at the given index.
     */
    @java.lang.Override
    public java.lang.String getItem(int index) {
      return instance.getItem(index);
    }
    /**
     * <code>repeated string item = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the item at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemBytes(int index) {
      return instance.getItemBytes(index);
    }
    /**
     * <code>repeated string item = 1;</code>
     * @param index The index to set the value at.
     * @param value The item to set.
     * @return This builder for chaining.
     */
    public Builder setItem(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setItem(index, value);
      return this;
    }
    /**
     * <code>repeated string item = 1;</code>
     * @param value The item to add.
     * @return This builder for chaining.
     */
    public Builder addItem(
        java.lang.String value) {
      copyOnWrite();
      instance.addItem(value);
      return this;
    }
    /**
     * <code>repeated string item = 1;</code>
     * @param values The item to add.
     * @return This builder for chaining.
     */
    public Builder addAllItem(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllItem(values);
      return this;
    }
    /**
     * <code>repeated string item = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItem() {
      copyOnWrite();
      instance.clearItem();
      return this;
    }
    /**
     * <code>repeated string item = 1;</code>
     * @param value The bytes of the item to add.
     * @return This builder for chaining.
     */
    public Builder addItemBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addItemBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:TextArray)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.nooriro.oneuplus.proto.googlecarrier.TextArray();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "item_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.nooriro.oneuplus.proto.googlecarrier.TextArray> parser = PARSER;
        if (parser == null) {
          synchronized (com.nooriro.oneuplus.proto.googlecarrier.TextArray.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.nooriro.oneuplus.proto.googlecarrier.TextArray>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:TextArray)
  private static final com.nooriro.oneuplus.proto.googlecarrier.TextArray DEFAULT_INSTANCE;
  static {
    TextArray defaultInstance = new TextArray();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TextArray.class, defaultInstance);
  }

  public static com.nooriro.oneuplus.proto.googlecarrier.TextArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TextArray> PARSER;

  public static com.google.protobuf.Parser<TextArray> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

