// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carriersettings.proto

package com.nooriro.oneuplus.proto.googlecarrier;

public interface VendorConfigsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VendorConfigs)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .VendorConfigClient client = 2;</code>
   */
  java.util.List<com.nooriro.oneuplus.proto.googlecarrier.VendorConfigClient> 
      getClientList();
  /**
   * <code>repeated .VendorConfigClient client = 2;</code>
   */
  com.nooriro.oneuplus.proto.googlecarrier.VendorConfigClient getClient(int index);
  /**
   * <code>repeated .VendorConfigClient client = 2;</code>
   */
  int getClientCount();
}
