#!/system/bin/sh
THIS="$(realpath "$0")"
THISDIR="${THIS%/*}"
MODDIR="${THISDIR%/*}"
sh "$MODDIR/scripts/one-uplus.sh"
kill "$(/system/bin/toybox ps -A -u radio | grep 'com\.android\.phone' | tr -s ' ' | cut -d ' ' -f 2)"
