#!/usr/bin/env bash
# Android NDK R21 (21.0.6113669)
# - Windows: https://dl.google.com/android/repository/android-ndk-r21-windows-x86_64.zip
# - Linux:   https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
NDK_ROOT="$HOME/android-ndk-r21"
cd "${0%/*}"
"$NDK_ROOT/ndk-build" -j 4 "$@"
find libs -type f -print0 | while IFS= read -r -d $'\0' F; do
  ./elf-cleaner "$F"
  "$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-objcopy" --strip-sections "$F"
done
cd - >/dev/null
